"""
WHY THIS FILE EXISTS

Reference values for js/src/numeric/, generated by scipy/numpy so the JavaScript kernel is measured
against the same library hyphaeon/*.py calls, over grids that reach into the tails the ports will
actually hit (chi2Sf out to LRT 1000, t.sf at |t| = 40 with df up to 2000, hypergeometric supports of
the sizes filter.py scans, betainc within 1e-12 of 0 and 1). fixtures/ (scripts/gen_fixtures.py)
covers the stats.py functions that wrap these; it does not exercise the primitives directly, which
is what this file is for. It is NOT a fixture in the fixtures/README.md sense: it lives with the
tests, and js/test/numeric-*.test.js reads its output.

Regenerate from js/ with the reference environment:

    python test/data/numeric/gen.py

Output: special.json, ranks.json, linalg.json in this directory. NaN and infinities are written as
the strings "NaN", "Infinity", "-Infinity" (the fixtures/README.md convention).
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

import numpy as np
import scipy
import scipy.special as sc
import scipy.stats as st

HERE = Path(__file__).resolve().parent
SEED = 20260904


def jsonable(v):
    if isinstance(v, (np.floating, float)):
        f = float(v)
        if math.isnan(f):
            return "NaN"
        if math.isinf(f):
            return "Infinity" if f > 0 else "-Infinity"
        return f
    if isinstance(v, (np.integer, int)):
        return int(v)
    if isinstance(v, np.ndarray):
        return [jsonable(x) for x in v.tolist()]
    if isinstance(v, (list, tuple)):
        return [jsonable(x) for x in v]
    if isinstance(v, dict):
        return {str(k): jsonable(x) for k, x in v.items()}
    return v


def write(name, payload):
    payload = {"generator": "js/test/data/numeric/gen.py", "scipy": scipy.__version__, "numpy": np.__version__, **payload}
    path = HERE / name
    path.write_text(json.dumps(jsonable(payload), indent=1) + "\n")
    print(f"wrote {path.relative_to(HERE.parent.parent.parent)}")


def gen_special():
    cases = []

    def add(fn, args, value):
        cases.append({"fn": fn, "args": list(args), "value": value})

    # lgamma: away from the zeros at 1 and 2 (relative error is meaningless there) plus the zeros
    # themselves, negative non-integers (log|Gamma|) and poles.
    for x in [1e-3, 0.01, 0.1, 0.25, 0.5, 0.75, 0.9, 1.0, 1.1, 1.5, 1.9, 2.0, 2.1, 2.5, 3.7, 5.0, 9.99, 10.0, 15.5,
              50.0, 100.5, 500.0, 1000.0, 1234.5, 1e4, 1e5, 1e6, -0.5, -2.5, -7.3]:
        add("lgamma", [x], sc.gammaln(x))
    for x in [0.0, -1.0, -5.0]:
        add("lgamma", [x], sc.gammaln(x))

    # regularized incomplete gamma, both tails
    a_grid = [0.5, 1.0, 1.5, 2.0, 2.5, 5.0, 10.0, 25.0, 50.0, 100.0, 500.0, 1000.0]
    x_grid = [0.0, 1e-8, 1e-3, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0, 100.0, 500.0, 1000.0, 2000.0]
    for a in a_grid:
        for x in x_grid + [0.6 * a, 0.9 * a, a, 1.1 * a, 1.4 * a]:
            add("gammaincReg", [a, x], sc.gammainc(a, x))
            add("gammaincc", [a, x], sc.gammaincc(a, x))

    # chi2 survival / cdf, the grid the task names plus more df
    for df in [1, 2, 3, 4, 10, 100, 1000]:
        for x in [0.0, 1e-8, 1e-4, 0.01, 0.5, 1.0, 3.84, 3.841, 6.635, 10.0, 10.83, 20.0, 50.0, 75.0, 100.0, 120.0,
                  200.0, 500.0, 1000.0, 1e4, 1e6]:
            add("chi2Sf", [x, df], st.chi2.sf(x, df))
            add("chi2Cdf", [x, df], st.chi2.cdf(x, df))
    add("chi2Sf", ["Infinity", 1], st.chi2.sf(np.inf, 1))
    add("chi2Sf", [-1.0, 1], st.chi2.sf(-1.0, 1))

    # regularized incomplete beta near 0 and 1 and across the middle
    # scipy 1.16 (Boost ibeta) is itself off by 3.5e-11 relative at betainc(0.5, 0.5, 1 - 1e-12)
    # (its a = b = 1/2 arcsine special case loses digits as sqrt(x) -> 1); mpmath at 40 digits is
    # the arbiter, and any point where scipy and mpmath disagree by more than 1e-13 relative is
    # recorded with the mpmath value and listed under `scipy_deviations`.
    import mpmath as mp
    mp.mp.dps = 40
    ab_grid = [0.5, 1.0, 2.0, 3.5, 10.0, 100.0, 1000.0]
    x_grid = [0.0, 1e-12, 1e-6, 1e-3, 0.01, 0.1, 0.3, 0.5, 0.7, 0.9, 0.99, 1 - 1e-3, 1 - 1e-6, 1 - 1e-12, 1.0]
    deviations = []
    for a in ab_grid:
        for b in ab_grid:
            for x in x_grid:
                v = float(sc.betainc(a, b, x))
                exact = float(mp.betainc(a, b, 0, mp.mpf(x), regularized=True))
                if exact != 0.0 and abs(v - exact) / abs(exact) > 1e-13:
                    deviations.append({"fn": "betaincReg", "args": [a, b, x], "scipy": v, "mpmath": exact,
                                       "rel": abs(v - exact) / abs(exact)})
                    v = exact
                add("betaincReg", [a, b, x], v)

    # Student t, |t| to 40, df 1..2000 including a non-integer df
    for df in [1, 2, 2.5, 3, 5, 10, 30, 100, 500, 2000]:
        for t in [0.0, 1e-6, 0.1, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 5.0, 10.0, 20.0, 40.0]:
            for sign in (1, -1):
                tt = sign * t
                add("tSf", [tt, df], st.t.sf(tt, df))
                add("tCdf", [tt, df], st.t.cdf(tt, df))
                if t == 0.0:
                    break
    add("tSf", ["Infinity", 5], st.t.sf(np.inf, 5))
    add("tSf", ["-Infinity", 5], st.t.sf(-np.inf, 5))

    # erfc and the normal tails
    for z in [0.0, 1e-10, 1e-3, 0.1, 0.46875, 0.47, 0.5, 1.0, 1.5, 2.0, 3.0, 3.99, 4.0, 4.01, 5.0, 8.0, 10.0, 20.0,
              26.0, 26.5, 30.0, 38.0]:
        for sign in (1, -1):
            zz = sign * z
            add("erfc", [zz], sc.erfc(zz))
            add("normSf", [zz], st.norm.sf(zz))
            add("normCdf", [zz], st.norm.cdf(zz))
            if z == 0.0:
                break
    add("erfc", ["Infinity"], sc.erfc(np.inf))
    add("erfc", ["-Infinity"], sc.erfc(-np.inf))

    # log-choose: exact via Python integers, plus the gamma form on reals
    for n, k in [(0, 0), (1, 0), (1, 1), (5, 2), (10, 3), (20, 10), (35, 3), (35, 17), (100, 50), (100, 3), (1000, 40),
                 (1000, 500), (3000, 35), (3000, 120), (3000, 1500), (10000, 64), (10000, 65), (10000, 5000),
                 (5, 6), (5, -1)]:
        if 0 <= k <= n:
            add("logChoose", [n, k], math.log(math.comb(n, k)))
        else:
            add("logChoose", [n, k], "-Infinity")
    for n, k in [(10.5, 3.2), (100.25, 40.75)]:
        add("logChoose", [n, k], sc.gammaln(n + 1) - sc.gammaln(k + 1) - sc.gammaln(n - k + 1))

    # hypergeometric over full supports (scipy order: k, M, n, N)
    hyper = []
    for (M, n, N) in [(20, 7, 12), (50, 25, 10), (100, 3, 35), (1000, 40, 35), (3000, 120, 35), (500, 250, 250),
                      (10, 0, 5), (10, 10, 3), (10, 4, 0), (10, 4, 10), (1, 1, 1), (2000, 60, 35), (36, 8, 35)]:
        lo = max(0, N - (M - n))
        hi = min(n, N)
        ks = list(range(lo - 2, hi + 3))
        hyper.append({
            "M": M, "n": n, "N": N, "lo": lo, "hi": hi, "k": ks,
            "pmf": [st.hypergeom.pmf(k, M, n, N) for k in ks],
            "cdf": [st.hypergeom.cdf(k, M, n, N) for k in ks],
            "sf": [st.hypergeom.sf(k, M, n, N) for k in ks],
            # the filter.py call shape: 1 - cdf(k - 1)
            "one_minus_cdf_km1": [1.0 - st.hypergeom.cdf(k - 1, M, n, N) for k in ks],
        })
    # non-integer k: pmf is 0; cdf/sf are 0/1 outside the support and NaN inside (scipy 1.16)
    hyper_noninteger = [{"k": k, "M": 20, "n": 7, "N": 12,
                         "pmf": st.hypergeom.pmf(k, 20, 7, 12), "cdf": st.hypergeom.cdf(k, 20, 7, 12),
                         "sf": st.hypergeom.sf(k, 20, 7, 12)} for k in [2.5, 3.999, -0.5, 7.5]]

    write("special.json", {"cases": cases, "hypergeom": hyper, "hypergeom_noninteger": hyper_noninteger,
                           "scipy_deviations": deviations})


def gen_ranks():
    rng = np.random.default_rng(SEED)
    sets = {}
    x = rng.normal(size=40)
    y = 0.6 * x + rng.normal(size=40)
    sets["gaussian_40"] = (x, y)
    xt = np.round(rng.normal(size=60), 1)  # many ties
    yt = np.round(0.3 * xt + rng.normal(size=60), 1)
    sets["ties_60"] = (xt, yt)
    sets["perfect"] = (np.arange(10.0), 2.0 * np.arange(10.0) + 1)
    sets["anti"] = (np.arange(10.0), -np.arange(10.0))
    sets["two"] = (np.array([1.0, 2.0]), np.array([5.0, 3.0]))
    lrt = rng.exponential(2.0, size=200).astype(np.float32).astype(np.float64)
    lrt[rng.integers(0, 200, 30)] = 0.0  # ties at zero, as the model emits
    sets["lrt_like_200"] = (lrt, rng.exponential(2.0, size=200))
    out = {}
    for name, (a, b) in sets.items():
        out[name] = {
            "x": a, "y": b,
            "rank_x": st.rankdata(a, method="average"),
            "rank_y": st.rankdata(b, method="average"),
            "pearson": st.pearsonr(a, b).statistic,
            "spearman": st.spearmanr(a, b).statistic,
        }
    # ROC-AUC, mirroring evaluation._roc_auc
    def roc(labels, scores):
        positives = int(labels.sum())
        negatives = len(labels) - positives
        if positives == 0 or negatives == 0:
            return None
        ranks = st.rankdata(scores, method="average")
        rank_sum = float(ranks[labels].sum())
        return (rank_sum - positives * (positives + 1) / 2.0) / (positives * negatives)

    rocs = {}
    for name, n in [("roc_100", 100), ("roc_ties_200", 200)]:
        scores = rng.exponential(2.0, size=n)
        if "ties" in name:
            scores = np.round(scores, 1)
        labels = (scores + rng.normal(scale=2.0, size=n)) > 2.0
        rocs[name] = {"labels": labels.astype(int), "scores": scores, "auc": roc(labels, scores)}
    rocs["all_positive"] = {"labels": [1, 1, 1], "scores": [0.1, 0.2, 0.3], "auc": None}
    rocs["all_negative"] = {"labels": [0, 0, 0], "scores": [0.1, 0.2, 0.3], "auc": None}
    rocs["perfect"] = {"labels": [0, 0, 1, 1], "scores": [0.1, 0.2, 0.3, 0.4], "auc": 1.0}
    rocs["all_tied"] = {"labels": [0, 1, 0, 1], "scores": [1.0, 1.0, 1.0, 1.0], "auc": 0.5}
    write("ranks.json", {"correlation": out, "roc": rocs})


def gen_linalg():
    rng = np.random.default_rng(SEED)
    mats = {}
    for name, n in [("spd_3", 3), ("spd_8", 8), ("gram_20", 20), ("spd_30", 30)]:
        if name.startswith("gram"):
            A = rng.normal(size=(n, 12)).astype(np.float32).astype(np.float64)
            S = A @ A.T  # rank-deficient Gram matrix (K > N), like epistasis.py:279
        else:
            B = rng.normal(size=(n, n))
            S = B @ B.T + n * np.eye(n)
        entry = {"n": n, "A": S, "eigvalsh": np.linalg.eigvalsh(S), "largest": float(np.linalg.eigvalsh(S)[-1])}
        try:
            entry["cholesky"] = np.linalg.cholesky(S)
        except np.linalg.LinAlgError:
            entry["cholesky"] = None
        mats[name] = entry
    # phenotype.py:323 shape: covariance + 1e-7 ridge
    V = np.array([[0.5, 0.2, 0.0], [0.2, 0.5, 0.1], [0.0, 0.1, 0.5]])
    mats["ridge_cov_3"] = {"n": 3, "A": V + 1e-7 * np.eye(3), "eigvalsh": np.linalg.eigvalsh(V + 1e-7 * np.eye(3)),
                           "largest": float(np.linalg.eigvalsh(V + 1e-7 * np.eye(3))[-1]),
                           "cholesky": np.linalg.cholesky(V + 1e-7 * np.eye(3))}
    mats["not_pd"] = {"n": 2, "A": np.array([[1.0, 2.0], [2.0, 1.0]]), "eigvalsh": np.linalg.eigvalsh([[1.0, 2.0], [2.0, 1.0]]),
                      "largest": 3.0, "cholesky": None}
    write("linalg.json", {"matrices": mats})


if __name__ == "__main__":
    gen_special()
    gen_ranks()
    gen_linalg()
    sys.exit(0)
