/**
 * WHY THIS FILE EXISTS
 *
 * Replays every case of fixtures/evaluation/*.json (generated by scripts/gen_fixtures.py from
 * hyphaeon/evaluation.py) against src/evaluate.js — `load_prediction_csv`, `load_meme_json`,
 * `_roc_auc`, `_correlations`, `evaluate_files` and its two error cases — at the fixture classes:
 * exact for counts, confusion matrices, site lists and messages, 1e-9 for correlations and AUC.
 * The inputs are read from fixtures/evaluation/inputs/ and handed over as {name, text} pairs, so
 * the report and the messages come out with the basenames the fixtures were reduced to.
 *
 * The fixtures exercise the loaders on well-formed files. The parser semantics the port
 * reproduces — Python's csv module, float(), int(), html.unescape, repr in messages — are checked
 * against test/data/evaluate/python_formatting.json, which the standard library itself produced
 * (see test/data/evaluate/gen.py), mostly THROUGH the public loaders so that what is pinned is the
 * behaviour a user can reach.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
	EvaluationError,
	loadPredictionCsv,
	loadMemeJson,
	matchGeneFiles,
	correlations,
	rocAuc,
	confusion,
	ppv,
	fpr,
	thresholdMetrics,
	evaluatePairs,
	evaluateDirectories,
	evaluateFiles,
	formatTextReport,
	parseCsvRows,
	dictReaderRows,
	normalizedHeader,
} from '../src/evaluate.js';
import { evaluateJson } from '../src/writers.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
const FIX = join(ROOT, 'fixtures', 'evaluation');
const loadFixture = (name) => JSON.parse(readFileSync(join(FIX, name), 'utf8'));
const input = (name) => readFileSync(join(FIX, 'inputs', name), 'utf8');
const file = (name) => ({ name, text: input(name) });
const ref = JSON.parse(readFileSync(join(HERE, 'data', 'evaluate', 'python_formatting.json'), 'utf8'));

/** A Map<number, record> as the fixture's string-keyed dict. */
function mapToObject(map) {
	const out = {};
	for (const [k, v] of map) out[String(k)] = v;
	return out;
}

/** Deep comparison at the fixture class: non-integer numbers within `tol`, everything else exact. */
function expectClose(got, want, tol, path = 'result') {
	if (typeof want === 'number' && !Number.isInteger(want)) {
		expect(typeof got, path).toBe('number');
		expect(Math.abs(got - want), `${path}: got ${got} want ${want}`).toBeLessThanOrEqual(tol);
	} else if (Array.isArray(want)) {
		expect(Array.isArray(got), path).toBe(true);
		expect(got.length, path).toBe(want.length);
		want.forEach((w, i) => expectClose(got[i], w, tol, `${path}[${i}]`));
	} else if (want !== null && typeof want === 'object') {
		expect(got !== null && typeof got === 'object', path).toBe(true);
		expect(Object.keys(got), `${path} keys`).toEqual(Object.keys(want));
		for (const k of Object.keys(want)) expectClose(got[k], want[k], tol, `${path}.${k}`);
	} else {
		expect(got, path).toEqual(want);
	}
}

describe('fixtures/evaluation/load_prediction_csv.json (evaluation.py:80-108)', () => {
	for (const c of loadFixture('load_prediction_csv.json')) {
		it(`${c.name} (${c.tolerance})`, () => {
			expect(c.tolerance).toBe('exact');
			const sites = loadPredictionCsv(input(c.inputs.file), c.inputs.file);
			expect(mapToObject(sites)).toEqual(c.outputs.sites);
			for (const s of sites.values()) expect(Object.keys(s)).toEqual(['lrt', 'p_value', 'is_invariable']);
		});
	}
});

describe('fixtures/evaluation/load_meme_json.json (evaluation.py:158-218)', () => {
	for (const c of loadFixture('load_meme_json.json')) {
		it(`${c.name} (${c.tolerance})`, () => {
			expect(c.tolerance).toBe('exact');
			const sites = loadMemeJson(input(c.inputs.file), c.inputs.file);
			expect(mapToObject(sites)).toEqual(c.outputs.sites);
			// The same document, already parsed, loads identically.
			const again = loadMemeJson(JSON.parse(input(c.inputs.file)), c.inputs.file);
			expect(mapToObject(again)).toEqual(c.outputs.sites);
		});
	}
	it('geneA: -0.0 is not clamped (max(0.0, -0.0) is +0.0), -0.04 is', () => {
		const sites = loadMemeJson(input('geneA.MEME.json'), 'geneA.MEME.json');
		expect(Object.is(sites.get(12).lrt, 0)).toBe(true);
		expect(sites.get(12).lrt_was_clamped).toBe(false);
		expect(sites.get(3)).toEqual({ lrt: 0, p_value: 0.6667, lrt_was_clamped: true });
	});
});

describe('fixtures/evaluation/roc_auc.json and correlations.json (evaluation.py:263-283)', () => {
	for (const c of loadFixture('roc_auc.json')) {
		it(`roc_auc ${c.name} (${c.tolerance})`, () => {
			const got = rocAuc(c.inputs.labels, c.inputs.scores);
			if (c.outputs.auc === null) expect(got).toBeNaN();
			else expect(Math.abs(got - c.outputs.auc)).toBeLessThanOrEqual(c.tolerance === 'exact' ? 0 : 1e-13);
		});
	}
	for (const c of loadFixture('correlations.json')) {
		it(`correlations ${c.name} (${c.tolerance})`, () => {
			const { pearson, spearman } = correlations(c.inputs.predicted, c.inputs.observed);
			if (c.outputs.pearson_r === null) {
				expect(pearson).toBeNull();
				expect(spearman).toBeNull();
			} else {
				expect(Math.abs(pearson - c.outputs.pearson_r)).toBeLessThanOrEqual(1e-13);
				expect(Math.abs(spearman - c.outputs.spearman_rho)).toBeLessThanOrEqual(1e-13);
			}
		});
	}
});

describe('fixtures/evaluation/evaluate_files.json (evaluation.py:497-527 over 330-449)', () => {
	const cases = loadFixture('evaluate_files.json');
	it('has the five cases the manifest records', () => {
		expect(cases.map((c) => c.name)).toEqual([
			'geneA_all_sites', 'geneA_variable_only', 'geneB_allow_site_mismatch', 'Smc6_example', 'Smc6_example_variable_only',
		]);
	});
	for (const c of cases) {
		it(`${c.name} (${c.tolerance})`, () => {
			expect(c.tolerance).toBe('1e-9');
			const got = evaluateFiles(file(c.inputs.prediction_file), file(c.inputs.meme_result_file), {
				allowSiteMismatch: c.inputs.allow_site_mismatch,
				variableOnly: c.inputs.variable_only,
			});
			expectClose(got, c.outputs.result, 1e-9);
			// The report round-trips through the Python-layout JSON writer unchanged.
			expectClose(JSON.parse(evaluateJson(got)), c.outputs.result, 1e-9);
		});
	}
	it('Smc6: correlations are at float64 rounding, far inside the class', () => {
		const c = cases.find((x) => x.name === 'Smc6_example');
		const got = evaluateFiles(file('Smc6.csv'), file('Smc6.MEME.json'));
		expect(Math.abs(got.pearson_r - c.outputs.result.pearson_r)).toBeLessThanOrEqual(1e-13);
		expect(Math.abs(got.spearman_rho - c.outputs.result.spearman_rho)).toBeLessThanOrEqual(1e-13);
		expect(Math.abs(got.thresholds['0.05'].roc_auc - c.outputs.result.thresholds['0.05'].roc_auc)).toBeLessThanOrEqual(1e-13);
	});
});

describe('fixtures/evaluation/evaluate_files_errors.json (exact messages)', () => {
	for (const c of loadFixture('evaluate_files_errors.json')) {
		it(`${c.name}: ${c.outputs.raises}`, () => {
			expect(c.outputs.raises).toBe('EvaluationError');
			let caught = null;
			try {
				evaluateFiles(file(c.inputs.prediction_file), file(c.inputs.meme_result_file));
			} catch (exc) {
				caught = exc;
			}
			expect(caught).toBeInstanceOf(EvaluationError);
			expect(caught).toBeInstanceOf(Error);
			expect(caught.message).toBe(c.outputs.message);
		});
	}
});

describe('csv.reader / csv.DictReader semantics (python_formatting.json)', () => {
	for (const [text, rows] of ref.csv_reader) {
		it(`reader ${JSON.stringify(text)}`, () => {
			expect(parseCsvRows(text)).toEqual(rows);
		});
	}
	for (const [text, fieldnames, rows] of ref.dict_reader) {
		it(`DictReader ${JSON.stringify(text)}`, () => {
			const got = dictReaderRows(text);
			expect(got.fieldnames).toEqual(fieldnames);
			const flat = got.rows.map(([n, d]) => [n, [...d.entries()].map(([k, v]) => [k === null ? 'None' : k, v])]);
			expect(flat).toEqual(rows);
		});
	}
});

describe('load_prediction_csv value parsing through the public loader', () => {
	const csvWith = (site, lrt, p, inv) => {
		const q = (s) => '"' + String(s).replace(/"/g, '""') + '"';
		return `site,hyphaeon_lrt,p_value,is_invariable\n${q(site)},${q(lrt)},${q(p)},${q(inv)}\n`;
	};
	const tryLoad = (text) => {
		try {
			return { sites: loadPredictionCsv(text, 'geneX.csv') };
		} catch (exc) {
			if (!(exc instanceof EvaluationError)) throw exc;
			return { message: exc.message };
		}
	};
	for (const [s, want] of ref.float_parse) {
		it(`float(${JSON.stringify(s)}) in hyphaeon_lrt`, () => {
			const r = tryLoad(csvWith('1', s, '0.5', 'True'));
			if (want === null) expect(r.message).toBe(`geneX.csv: hyphaeon_lrt is not numeric: ${pyQuote(s)}`);
			else if (want === 'nan' || want === 'inf' || want === '-inf') expect(r.message).toBe(`geneX.csv: hyphaeon_lrt must be finite, got ${pyQuote(s)}`);
			else if (Number(want) < 0) expect(r.message).toBe('geneX.csv:2: hyphaeon_lrt cannot be negative');
			else expect(r.sites.get(1).lrt).toBe(Number(want));
		});
	}
	for (const [v, want] of ref.boolean) {
		if (v === null) continue;
		it(`_boolean(${JSON.stringify(v)})`, () => {
			const r = tryLoad(csvWith('1', '0.5', '0.5', v));
			if (typeof want === 'boolean') expect(r.sites.get(1).is_invariable).toBe(want);
			else expect(r.message).toBe(want);
		});
	}
	it('_boolean(None): a short row leaves is_invariable None', () => {
		const want = ref.boolean.find(([v]) => v === null)[1];
		expect(tryLoad('site,hyphaeon_lrt,p_value,is_invariable\n1,0.5,0.5\n').message).toBe(want);
	});
	for (const [v, want] of ref.probability_messages) {
		if (typeof v !== 'string') continue;
		it(`_probability(${JSON.stringify(v)})`, () => {
			const r = tryLoad(csvWith('1', '0.5', v, 'True'));
			if (want === 'ok') expect(r.sites.get(1).p_value).toBe(Number(v));
			else expect(r.message).toBe(want);
		});
	}
	for (const [v, want] of ref.site_number_messages) {
		if (typeof v !== 'string') continue;
		it(`_site_number(${JSON.stringify(v)})`, () => {
			const r = tryLoad(csvWith(v, '0.5', '0.5', 'True'));
			if (typeof want === 'number') expect([...r.sites.keys()]).toEqual([want]);
			else expect(r.message).toBe(want);
		});
	}
	it('structural errors: missing columns, duplicate site, no sites, blank first line', () => {
		expect(tryLoad('site,p_value\n1,0.5\n').message).toBe('geneX.csv: missing required CSV column(s): hyphaeon_lrt, is_invariable');
		expect(tryLoad('').message).toBe('geneX.csv: missing required CSV column(s): hyphaeon_lrt, is_invariable, p_value, site');
		expect(tryLoad('\nsite,hyphaeon_lrt,p_value,is_invariable\n1,0.5,0.5,True\n').message).toBe(
			'geneX.csv: missing required CSV column(s): hyphaeon_lrt, is_invariable, p_value, site',
		);
		expect(tryLoad('site,hyphaeon_lrt,p_value,is_invariable\n').message).toBe('geneX.csv: prediction CSV contains no sites');
		expect(tryLoad('site,hyphaeon_lrt,p_value,is_invariable\n1,0.5,0.5,True\n\n1,0.5,0.5,True\n').message).toBe('geneX.csv:3: duplicate site 1');
		expect(tryLoad('﻿site,hyphaeon_lrt,p_value,is_invariable\n2,0.5,0.5,yes\n').sites.get(2)).toEqual({ lrt: 0.5, p_value: 0.5, is_invariable: true });
		expect(tryLoad('site,hyphaeon_lrt,p_value,is_invariable\r\n3,1e-3,0.25,0\r\n').sites.get(3)).toEqual({ lrt: 0.001, p_value: 0.25, is_invariable: false });
	});
});

/** Python repr of a plain string for the messages above (the pyRepr in writers.js is tested there). */
function pyQuote(s) {
	const quote = s.includes("'") && !s.includes('"') ? '"' : "'";
	let out = '';
	for (const ch of s) {
		const cp = ch.codePointAt(0);
		if (ch === '\\') out += '\\\\';
		else if (ch === quote) out += '\\' + quote;
		else if (ch === '\n') out += '\\n';
		else if (ch === '\t') out += '\\t';
		else if (cp < 0x20 || cp === 0x7f) out += '\\x' + cp.toString(16).padStart(2, '0');
		else out += ch;
	}
	return quote + out + quote;
}

describe('load_meme_json semantics through the public loader', () => {
	const doc = (content, extra = {}) => ({ MLE: { content, ...extra.mle }, ...extra.top });
	const row = (lrt, p) => [0.1, 0.2, 0.3, 0.4, 0.5, lrt, p, 1];
	for (const [h, want] of ref.normalized_header) {
		it(`_normalized_header(${JSON.stringify(h)}) == ${JSON.stringify(want)}`, () => {
			expect(normalizedHeader(h)).toBe(want);
		});
	}
	it('headers select the columns; more than one match is an error; none falls back to 5/6', () => {
		const withHeaders = doc({ 0: [[2.5, 0.1]] }, { mle: { headers: [['<b>LRT</b>', ''], ['p&#45;value', '']] } });
		expect(loadMemeJson(withHeaders, 'x').get(1)).toEqual({ lrt: 2.5, p_value: 0.1, lrt_was_clamped: false });
		const dup = doc({ 0: [[1, 0.1, 2]] }, { mle: { headers: ['LRT', 'lrt', 'p-value'] } });
		expect(() => loadMemeJson(dup, 'x')).toThrow("x: MEME has more than one 'lrt' column");
		expect(loadMemeJson(doc({ 0: [row(1.5, 0.2)] }), 'x').get(1)).toEqual({ lrt: 1.5, p_value: 0.2, lrt_was_clamped: false });
	});
	it('partitions sort by _partition_key: numeric (int() semantics) ascending, then strings', () => {
		const content = { 10: [row(10, 0.5)], b: [row(60, 0.5)], '007': [row(7, 0.5)], ' 2 ': [row(2, 0.5)], '٣': [row(3, 0.5)], '1.0': [row(50, 0.5)] };
		const sites = loadMemeJson(doc(content), 'x');
		expect([...sites.values()].map((s) => s.lrt)).toEqual([2, 3, 7, 10, 50, 60]);
		expect([...sites.keys()]).toEqual([1, 2, 3, 4, 5, 6]);
	});
	for (const [s, want] of ref.int_parse) {
		it(`int(${JSON.stringify(s)}) as a partition key`, () => {
			const content = { [s]: [row(1, 0.5)], zzz: [row(2, 0.5)] };
			const sites = loadMemeJson(doc(content), 'x');
			// A numeric key sorts before the string key 'zzz'; a non-numeric key sorts by string order.
			const first = sites.get(1).lrt;
			if (want !== null) expect(first).toBe(1);
			else expect(first).toBe(s < 'zzz' ? 1 : 2);
		});
	}
	it('coverage recovers global site ids; the fallback continues after the highest covered index', () => {
		const d = doc({ 1: [row(1, 0.5), row(2, 0.5)], 0: [row(3, 0.5)], 2: [row(4, 0.5)] }, { top: { 'data partitions': { 1: { coverage: [[5], [[7]]] } } } });
		const sites = loadMemeJson(d, 'x');
		expect([...sites.entries()].map(([k, v]) => [k, v.lrt])).toEqual([[1, 3], [6, 1], [8, 2], [9, 4]]);
	});
	it('error messages (exact Python text)', () => {
		const bad = (value, msg) => expect(() => loadMemeJson(value, 'm.json')).toThrow(msg);
		bad('{', 'Could not read MEME JSON m.json: ');
		bad({}, 'm.json: expected an MLE.content object');
		bad({ MLE: { content: [] } }, 'm.json: expected an MLE.content object');
		bad([], 'm.json: expected an MLE.content object');
		bad(doc({}), 'm.json: MLE.content contains no partitions');
		bad(doc({ 0: {} }), "m.json: MLE.content['0'] must be a list");
		bad(doc({ 0: [row(1, 0.5)] }, { top: { 'data partitions': { 0: { coverage: [0, 1] } } } }), "m.json: partition '0' has 1 MLE rows but 2 covered sites");
		bad(doc({ 0: [row(1, 0.5)] }, { top: { 'data partitions': { 0: { coverage: ['a'] } } } }), "m.json: invalid site index in data partition '0' coverage");
		bad(doc({ 0: [row(1, 0.5)] }, { top: { 'data partitions': { 0: { coverage: [true] } } } }), "m.json: invalid site index in data partition '0' coverage");
		bad(doc({ 0: [row(1, 0.5)] }, { top: { 'data partitions': { 0: { coverage: [1.5] } } } }), "m.json: invalid site index 1.5 in partition '0' coverage");
		bad(doc({ 0: [row(1, 0.5)] }, { top: { 'data partitions': { 0: { coverage: [-1] } } } }), "m.json: invalid site index -1 in partition '0' coverage");
		bad(doc({ 0: [[1, 2]] }), "m.json: partition '0' row 1 lacks LRT/p-value columns");
		bad(doc({ 0: [row(1, 0.5), 'x'] }), "m.json: partition '0' row 2 lacks LRT/p-value columns");
		bad(doc({ 0: [row(1, 0.5)], 1: [row(1, 0.5)] }, { top: { 'data partitions': { 1: { coverage: [0] } } } }), 'm.json: duplicate MEME site 1 across partitions');
		bad(doc({ 0: [row('abc', 0.5)] }), "m.json: MEME LRT is not numeric: 'abc'");
		bad(doc({ 0: [row(null, 0.5)] }), 'm.json: MEME LRT is not numeric: None');
		bad(doc({ 0: [row([1], 0.5)] }), 'm.json: MEME LRT is not numeric: [1]');
		bad(doc({ 0: [row('inf', 0.5)] }), "m.json: MEME LRT must be finite, got 'inf'");
		bad(doc({ 0: [row(1, 1.5)] }), 'm.json: MEME p-value must be between 0 and 1, got 1.5');
		bad(doc({ 0: [row(1, '2')] }), 'm.json: MEME p-value must be between 0 and 1, got 2.0');
		bad(doc({ 0: [] }), 'm.json: MEME JSON contains no sites');
		// Strings parse with float() and a bool is 1.0, as in Python.
		expect(loadMemeJson(doc({ 0: [row('1e0', '0.5')] }), 'x').get(1)).toEqual({ lrt: 1, p_value: 0.5, lrt_was_clamped: false });
		expect(loadMemeJson(doc({ 0: [row(true, true)] }), 'x').get(1)).toEqual({ lrt: 1, p_value: 1, lrt_was_clamped: false });
	});
	for (const [v, want] of ref.probability_messages) {
		if (typeof v === 'string') continue;
		it(`_probability(${JSON.stringify(v)}) from JSON`, () => {
			const expected = typeof want === 'string' ? want.replace('geneX.csv: p_value', 'x: MEME p-value') : want;
			if (expected === 'ok') expect(loadMemeJson(doc({ 0: [row(1, v)] }), 'x').get(1).p_value).toBe(Number(v));
			else expect(() => loadMemeJson(doc({ 0: [row(1, v)] }), 'x')).toThrow(expected);
		});
	}
});

describe('match_gene_files / evaluate_directories (evaluation.py:221-260, 452-483)', () => {
	const preds = () => [file('geneA.csv'), file('geneB.csv'), { name: 'notes.txt', text: '' }];
	const memes = () => [file('geneA.MEME.json'), file('geneB.MEME.json')];
	it('pairs genes by stripping suffixes, sorted', () => {
		const { pairs, predictionOnly, memeOnly } = matchGeneFiles(preds().reverse(), memes());
		expect(pairs.map((p) => p.gene)).toEqual(['geneA', 'geneB']);
		expect(pairs[0].prediction.name).toBe('geneA.csv');
		expect(pairs[1].meme.name).toBe('geneB.MEME.json');
		expect(predictionOnly).toEqual([]);
		expect(memeOnly).toEqual([]);
	});
	it('unmatched files fail unless allowed, then become warnings in the report', () => {
		expect(() => matchGeneFiles(preds(), memes().slice(0, 1))).toThrow('Unmatched input files; prediction-only genes: geneB');
		expect(() => matchGeneFiles(preds().slice(0, 1), memes())).toThrow('Unmatched input files; MEME-only genes: geneB');
		expect(() => matchGeneFiles([file('geneA.csv')], [file('geneB.MEME.json')])).toThrow(
			'Unmatched input files; prediction-only genes: geneA; MEME-only genes: geneB',
		);
		expect(() => matchGeneFiles([file('geneA.csv')], [file('geneB.MEME.json')], { allowUnmatched: true })).toThrow(
			'The two directories contain no matching gene names',
		);
		const report = evaluateDirectories(preds(), memes().slice(0, 1), {
			allowUnmatched: true,
			predictionDirectory: '/data/preds',
			memeDirectory: '/data/meme',
		});
		expect(report.input_mode).toBe('directories');
		expect(report.prediction_directory).toBe('/data/preds');
		expect(report.meme_directory).toBe('/data/meme');
		expect(report.genes).toEqual(['geneA']);
		expect(report.warnings).toEqual(['Ignored prediction-only genes: geneB', 'Clamped 1 negative MEME LRT numerical artifact(s) to zero']);
		expect(Object.keys(report).slice(0, 4)).toEqual(['input_mode', 'prediction_directory', 'meme_directory', 'matched_genes']);
	});
	it('directory-level errors (exact Python text)', () => {
		expect(() => matchGeneFiles([{ name: 'x.txt', text: '' }], memes(), { predictionDirectory: 'preds' })).toThrow(
			'No *.csv files found in prediction directory preds',
		);
		expect(() => matchGeneFiles(preds(), [], { memeDirectory: 'm' })).toThrow('No *.MEME.json files found in MEME directory m');
		expect(() => matchGeneFiles([file('geneA.csv'), { name: 'geneA.csv', text: '' }], memes())).toThrow(
			"prediction directory has duplicate files for gene 'geneA'",
		);
		expect(() => matchGeneFiles([{ name: '.csv', text: '' }], memes())).toThrow(".csv: file name has no gene name before '.csv'");
		expect(() => matchGeneFiles(preds(), memes(), { predictionSuffix: '' })).toThrow('Unmatched input files; prediction-only genes: geneA.csv, geneB.csv, notes.txt; MEME-only genes: geneA, geneB');
	});
	it('pooling over two genes sums the per-gene counts', () => {
		const report = evaluateDirectories(preds(), memes(), { allowSiteMismatch: true });
		expect(report.matched_genes).toBe(2);
		expect(report.total_sites).toBe(24);
		expect(report.total_prediction_sites).toBe(25);
		expect(report.evaluated_sites).toBe(24);
		expect(report.per_gene.map((g) => g.gene)).toEqual(['geneA', 'geneB']);
		expect(report.warnings).toEqual([
			'Site intersection used; dropped 1 prediction-only and 0 MEME-only sites',
			'Clamped 2 negative MEME LRT numerical artifact(s) to zero',
		]);
		expect(() => evaluateDirectories(preds(), memes())).toThrow("Gene 'geneB' has mismatched sites: prediction-only sites [13]");
	});
});

describe('evaluate_files edge cases and evaluatePairs (evaluation.py:330-449, 486-527)', () => {
	it('single-gene suffix checks', () => {
		expect(() => evaluateFiles({ name: 'geneA.txt', text: '' }, file('geneA.MEME.json'))).toThrow("prediction file must end with '.csv': geneA.txt");
		expect(() => evaluateFiles(file('geneA.csv'), { name: 'geneA.json', text: '' })).toThrow("MEME result file must end with '.MEME.json': geneA.json");
		expect(() => evaluateFiles({ name: '.csv', text: '' }, file('geneA.MEME.json'))).toThrow(".csv: file name has no gene name before '.csv'");
		const r = evaluateFiles({ name: 'geneA', text: input('geneA.csv') }, { name: 'geneA', data: JSON.parse(input('geneA.MEME.json')) }, { predictionSuffix: '', memeSuffix: '' });
		expect(r.genes).toEqual(['geneA']);
		expect(r.prediction_file).toBe('geneA');
	});
	it('no evaluable sites', () => {
		const allInvariable = 'site,hyphaeon_lrt,p_value,is_invariable\n1,0.0,0.6667,True\n2,0.0,0.6667,True\n';
		const meme = { MLE: { content: { 0: [[0, 0, 0, 0, 0, 0.0, 1.0], [0, 0, 0, 0, 0, 0.0, 1.0]] } } };
		expect(() => evaluateFiles({ name: 'g.csv', text: allInvariable }, { name: 'g.MEME.json', data: meme }, { variableOnly: true })).toThrow(
			'No variable sites are available for evaluation',
		);
		const r = evaluateFiles({ name: 'g.csv', text: allInvariable }, { name: 'g.MEME.json', data: meme });
		expect(r.pearson_r).toBeNull();
		expect(r.spearman_rho).toBeNull();
		expect(r.thresholds['0.05'].roc_auc).toBeNull();
		expect(r.thresholds['0.05'].ppv).toBeNull();
		expect(r.thresholds['0.05'].fpr).toBe(0);
		expect(r.thresholds['0.10'].ppv_confusion_matrix).toEqual({ true_positive: 0, false_positive: 0, true_negative: 2, false_negative: 0 });
		expect(() => evaluatePairs([])).toThrow('No matched sites are available for evaluation');
		const noShared = 'site,hyphaeon_lrt,p_value,is_invariable\n5,0.0,0.6667,True\n';
		expect(() => evaluateFiles({ name: 'g.csv', text: noShared }, { name: 'g.MEME.json', data: meme }, { allowSiteMismatch: true })).toThrow(
			"Gene 'g' has no sites shared by its two result files",
		);
		expect(() => evaluateFiles({ name: 'g.csv', text: noShared }, { name: 'g.MEME.json', data: meme })).toThrow(
			"Gene 'g' has mismatched sites: prediction-only sites [5]; MEME-only sites [1, 2]",
		);
	});
	it('threshold arithmetic: inclusive <=, alpha printed with %g', () => {
		const m = thresholdMetrics([3, 1, 2, 0], [0.05, 0.2, 0.01, 0.1], [0.05, 0.1, 0.5, 0.1], 0.1);
		expect(m.meme_positive_sites).toBe(3);
		expect(m.hyphaeon_positive_sites).toBe(3);
		expect(m.roc_auc_definition).toBe('ground truth MEME p_value <= 0.1; score = HyphAeon hyphaeon_lrt');
		expect(m.ppv_definition).toBe('MEME and HyphAeon p_value <= 0.1');
		expect(m.ppv_confusion_matrix).toEqual({ true_positive: 2, false_positive: 1, true_negative: 0, false_negative: 1 });
		expect(m.fpr).toBe(1);
		expect(ppv({ true_positive: 0, false_positive: 0 })).toBeNull();
		expect(fpr({ false_positive: 0, true_negative: 0 })).toBeNull();
		expect(confusion([true, false], [false, false])).toEqual({ true_positive: 0, false_positive: 0, true_negative: 1, false_negative: 1 });
		expect(thresholdMetrics([1], [0.01], [0.01], 0.05).ppv_definition).toBe('MEME and HyphAeon p_value <= 0.05');
	});
});

describe('format_text_report (evaluation.py:530-553)', () => {
	for (const [i, c] of ref.text_report.entries()) {
		it(`reference text ${i}`, () => {
			expect(formatTextReport(c.result)).toBe(c.text);
		});
	}
	it('renders the fixture reports without trailing newline and with 6-decimal fixed columns', () => {
		const r = evaluateFiles(file('geneA.csv'), file('geneA.MEME.json'));
		const text = formatTextReport(r);
		expect(text.endsWith('\n')).toBe(false);
		expect(text.split('\n')[3]).toBe('Pearson r (LRT): 0.922116');
		expect(text.split('\n')[7]).toBe('ROC-AUC                  1.000000      0.944444');
	});
});
