/**
 * fixtures.test.js — the fixture replay for hyphaeon/dataset.py.
 *
 * WHY THIS FILE EXISTS
 *
 * PLAN.md §5.3 rule 2: fixtures are generated by Python (scripts/gen_fixtures.py) and replayed
 * here, so a change to a method without a matching change to its port fails in the same pull
 * request. This file (1) checks fixtures/manifest.json against the files on disk and (2) replays
 * EVERY fixtures/dataset/*.json against src/preprocess/:
 *
 *   tokenizer                       tables and tokens, exact
 *   parse_alignment_sequences       every examples/*.fasta (names, lengths, sha256 of the
 *                                   concatenated sequences) and the synthetic PHYLIP/NEXUS/FASTA/gz
 *                                   inputs (exact, quirks included)
 *   extract_tree_from_string_or_file terminals, terminal branch lengths, clade count, the
 *                                   has_nonzero_branch_lengths flag, and the None cases
 *   compute_fast_dist_matrix        Smc6 and bat_oas1, 1e-6
 *   compute_mds_coordinates         1e-5 EXACT per column (canonical signs), plus the Gram matrix
 *   rescale_rule                    the four synthetic trees, 1e-6
 *   prune_identical_sequences       exact
 *   load_alignment_and_tree_duplicates  exact tokens/mask, 1e-6 distances
 *   downsample_taxa_faith_pd        exact taxa, 1e-6 sub-matrix (camelid 128 -> 64 included)
 *   load_alignment_and_tree         Smc6 and bat_oas1 end to end
 *
 * MDS SIGN CONVENTION: dataset.py canonicalises eigenvector signs (largest-|entry| of each kept
 * column positive, first index on ties, before the sqrt(eigenvalue) scaling; `mds_sign="canonical"`,
 * the default) and mds.js applies the same rule, so `z` is compared EXACTLY per column at the 1e-5
 * class — no sign-flip allowance (fixtures/README.md "MDS sign convention"; MDS_SIGN.md). Before the
 * fixtures were regenerated with that default this file compared min(|js - py|, |js + py|) per column;
 * that allowance is gone on purpose: a sign disagreement is now a defect, because the model is not
 * sign-invariant. The sign-invariant Gram matrix is still compared as a second check. Where the top
 * eigenvalues are degenerate (the equilateral triangle case) only the Gram matrix is meaningful;
 * that case is compared on Gram alone.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync, statSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { codonToken, aaToken, GENETIC_CODE, AA_MAP, CODON_TO_AA } from '../src/preprocess/tokenizer.js';
import { parseAlignmentSequences } from '../src/preprocess/parse.js';
import {
	extractTree,
	getTerminals,
	findClades,
	hasNonzeroBranchLengths,
	enforceNonzeroBranchLengths,
	treeTaxa
} from '../src/preprocess/tree.js';
import { computeFastDistMatrix } from '../src/preprocess/patristic.js';
import { computeMdsCoordinates } from '../src/preprocess/mds.js';
import { pruneIdenticalSequences, downsampleTaxaFaithPd } from '../src/preprocess/downsample.js';
import { loadAlignmentAndTree } from '../src/preprocess/assemble.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const FIXTURES = join(ROOT, 'fixtures');
const EXAMPLES = join(ROOT, 'examples');

function loadJson(rel) {
	return JSON.parse(readFileSync(join(FIXTURES, rel), 'utf8'));
}
const readExample = (name) => readFileSync(join(EXAMPLES, name), 'utf8');
const readInput = (name) => readFileSync(join(FIXTURES, 'dataset', 'inputs', name), 'utf8');

/** Numeric tolerance from a fixture's `tolerance` field. */
function tol(c) {
	return c.tolerance === 'exact' ? 0 : Number(c.tolerance);
}

/** max |a - b| over two flat arrays of equal length. */
function maxAbsDiff(a, b) {
	expect(a.length).toBe(b.length);
	let worst = 0;
	for (let i = 0; i < a.length; i++) worst = Math.max(worst, Math.abs(a[i] - b[i]));
	return worst;
}

/** max |js - py| over an n x k column-major-by-row JS array against the fixture's row lists. */
function maxColumnDiff(jsFlat, pyRows, n, k) {
	let worst = 0;
	for (let col = 0; col < k; col++) {
		for (let i = 0; i < n; i++) worst = Math.max(worst, Math.abs(jsFlat[i * k + col] - pyRows[i][col]));
	}
	return worst;
}

/** coords @ coords.T from a flat [n, k] array. */
function gram(flat, n, k) {
	const g = new Float64Array(n * n);
	for (let i = 0; i < n; i++)
		for (let j = 0; j < n; j++) {
			let s = 0;
			for (let c = 0; c < k; c++) s += flat[i * k + c] * flat[j * k + c];
			g[i * n + j] = s;
		}
	return g;
}

const flat = (rows) => rows.flat();

/** float32 machine epsilon: the reference's eigendecomposition runs in float32 (LAPACK ssyevd). */
const EPS32 = 2 ** -23;

/**
 * The MDS tolerance, as the fixture records it: `tolerance_relative: true, tolerance_floor: 1`
 * (gen_fixtures.py MDS_RELATIVE) means tol * max(floor, |compared magnitude|). The reference forms
 * B and runs eigh in float32, so its own rounding at a coordinate of magnitude m is ~m * 6e-8, and
 * bat_oas1's RAW (unrescaled) distances give coordinates of magnitude ~60 — an absolute 1e-5 is
 * below the reference's own ULP there. The floor of 1 makes it the plain absolute 1e-5 for
 * everything of order 1 or less (both load_alignment_and_tree cases, Smc6, bat_oas1 rescaled).
 * A case without the relative flag gets its absolute class.
 */
function mdsTol(c, magnitude) {
	return c.tolerance_relative ? tol(c) * Math.max(c.tolerance_floor ?? 1, magnitude) : tol(c);
}

/**
 * Per-column EXACT comparison (canonical signs on both sides; no sign-flip allowance), with a noise
 * floor: a component whose eigenvalue is below float32 resolution of the spectrum (eps32 *
 * lambda_max, i.e. a coordinate below sqrt(eps32 * max Gram entry)) is rounding noise on BOTH sides
 * — the synthetic 2-D case's 3rd and 4th components have eigenvalues 2e-7 and 5e-9 against 10.7 —
 * so its pivot, and hence its canonical sign, is solver-dependent; it is only required to stay below
 * that floor here too. Every other column must match the reference including its sign.
 */
function checkMdsColumns(c, jsFlat, pyRows, n, k, gramMax) {
	const noiseFloor = Math.sqrt(EPS32 * gramMax);
	for (let col = 0; col < k; col++) {
		let same = 0;
		let pyMag = 0;
		let jsMag = 0;
		for (let i = 0; i < n; i++) {
			const js = jsFlat[i * k + col];
			const py = pyRows[i][col];
			same = Math.max(same, Math.abs(js - py));
			pyMag = Math.max(pyMag, Math.abs(py));
			jsMag = Math.max(jsMag, Math.abs(js));
		}
		if (pyMag < noiseFloor) {
			expect(jsMag, `${c.name} column ${col} is below the float32 noise floor in the reference`).toBeLessThan(noiseFloor);
		} else {
			expect(same, `${c.name} column ${col} exact (canonical sign)`).toBeLessThanOrEqual(mdsTol(c, pyMag));
		}
	}
}

describe('fixtures/manifest.json agrees with the files on disk', () => {
	const manifest = loadJson('manifest.json');

	it('names the generator, the engine commit and the weights it ran with', () => {
		expect(manifest.generator).toBe('scripts/gen_fixtures.py');
		expect(manifest.engine_commit).toMatch(/^[0-9a-f]{40}$/);
		expect(manifest.model_safetensors_sha256).toMatch(/^[0-9a-f]{64}$/);
	});

	it('lists every fixture file with its byte size', () => {
		for (const [rel, bytes] of Object.entries(manifest.bytes)) {
			expect(existsSync(join(FIXTURES, rel)), `${rel} missing`).toBe(true);
			expect(statSync(join(FIXTURES, rel)).size, `${rel} size`).toBe(bytes);
		}
		const total = Object.values(manifest.bytes).reduce((a, b) => a + b, 0);
		expect(total).toBe(manifest.total_bytes);
	});

	it('records a case count that matches each file', () => {
		for (const [module, fns] of Object.entries(manifest.counts)) {
			for (const [fn, n] of Object.entries(fns)) {
				const cases = loadJson(`${module}/${fn}.json`);
				expect(Array.isArray(cases), `${module}/${fn}.json is a list`).toBe(true);
				expect(cases.length, `${module}/${fn}.json cases`).toBe(n);
				for (const c of cases) {
					expect(typeof c.name).toBe('string');
					expect(c).toHaveProperty('inputs');
					expect(c).toHaveProperty('outputs');
					expect(c).toHaveProperty('tolerance');
				}
			}
		}
	});

	it('carries no absolute paths', () => {
		for (const rel of Object.keys(manifest.bytes)) {
			expect(readFileSync(join(FIXTURES, rel), 'utf8')).not.toContain('/Users/');
		}
	});
});

describe('dataset/tokenizer.json', () => {
	const cases = loadJson('dataset/tokenizer.json');
	for (const c of cases) {
		it(c.name, () => {
			if (c.name === 'tables') {
				expect(Object.fromEntries(GENETIC_CODE)).toEqual(c.outputs.GENETIC_CODE);
				expect(Object.fromEntries(AA_MAP)).toEqual(c.outputs.AA_MAP);
				expect(Object.fromEntries(CODON_TO_AA)).toEqual(c.outputs.CODON_TO_AA);
				return;
			}
			expect(c.inputs.codons.map(codonToken)).toEqual(c.outputs.codon_tokens);
			expect(c.inputs.codons.map(aaToken)).toEqual(c.outputs.aa_tokens);
		});
	}
});

describe('dataset/parse_alignment_sequences.json', () => {
	const cases = loadJson('dataset/parse_alignment_sequences.json');
	for (const c of cases) {
		it(c.name, () => {
			let text;
			if (c.name.startsWith('example_')) text = readExample(c.inputs.file);
			else if (c.inputs.text === null) {
				text = gunzipSync(readFileSync(join(FIXTURES, 'dataset', 'inputs', c.inputs.file))).toString('utf8');
			} else {
				text = c.inputs.text;
				// The stored text is the file's content.
				expect(readInput(c.inputs.file)).toBe(text);
			}
			const seqs = parseAlignmentSequences(text);
			if (c.outputs.sequences) {
				expect(Object.fromEntries(seqs)).toEqual(c.outputs.sequences);
				expect([...seqs.keys()]).toEqual(Object.keys(c.outputs.sequences));
				return;
			}
			expect(seqs.size).toBe(c.outputs.n_sequences);
			expect([...seqs.keys()]).toEqual(c.outputs.names);
			expect([...seqs.values()].map((s) => s.length)).toEqual(c.outputs.lengths);
			for (const [name, seq] of Object.entries(c.outputs.first_5)) expect(seqs.get(name)).toBe(seq);
			const sha = createHash('sha256').update([...seqs.values()].join(''), 'utf8').digest('hex');
			expect(sha).toBe(c.outputs.sha256_of_concatenated_sequences);
		});
	}
});

describe('dataset/extract_tree_from_string_or_file.json', () => {
	const cases = loadJson('dataset/extract_tree_from_string_or_file.json');
	for (const c of cases) {
		it(c.name, () => {
			// `inputs.source` is the tree text itself, for the example files too.
			const tree = extractTree(c.inputs.source);
			if (c.outputs.tree === null) {
				expect(tree).toBeNull();
				return;
			}
			expect(tree).not.toBeNull();
			if (c.notes.includes('Output after enforce_nonzero_branch_lengths')) {
				enforceNonzeroBranchLengths(tree, 1e-4);
			}
			const terms = getTerminals(tree);
			expect(terms.map((t) => tree.name[t])).toEqual(c.outputs.tree.terminals);
			expect(terms.map((t) => tree.branchLength[t])).toEqual(c.outputs.tree.terminal_branch_lengths);
			expect(findClades(tree).length).toBe(c.outputs.tree.n_clades);
			expect(hasNonzeroBranchLengths(tree)).toBe(c.outputs.tree.has_nonzero_branch_lengths);
		});
	}
});

describe('dataset/compute_fast_dist_matrix.json', () => {
	const cases = loadJson('dataset/compute_fast_dist_matrix.json');
	for (const c of cases) {
		it(c.name, () => {
			const tree = extractTree(c.inputs.newick);
			expect(tree).not.toBeNull();
			enforceNonzeroBranchLengths(tree, 1e-4);
			const taxa = c.inputs.taxa;
			const d = computeFastDistMatrix(tree, taxa);
			const py = flat(c.outputs.dist_matrix);
			expect(maxAbsDiff(d, py)).toBeLessThanOrEqual(tol(c));
			expect(Math.max(...d)).toBeCloseTo(c.outputs.max, 6);
		});
	}
});

describe('dataset/compute_mds_coordinates.json', () => {
	const cases = loadJson('dataset/compute_mds_coordinates.json');
	for (const c of cases) {
		it(c.name, () => {
			const rows = c.inputs.dist_matrix;
			const n = rows.length;
			const k = c.inputs.n_components;
			// The fixture records inputs.mds_sign = "canonical"; the library's default is the same rule.
			expect(c.inputs.mds_sign).toBe('canonical');
			// And the relative class with floor 1 (the generator's MDS_RELATIVE convention).
			expect(c.tolerance_relative).toBe(true);
			expect(c.tolerance_floor).toBe(1);
			const z = computeMdsCoordinates(Float32Array.from(flat(rows)), n, k, { mdsSign: c.inputs.mds_sign });
			const pyGram = flat(c.outputs.gram);
			const gramMax = Math.max(...pyGram.map(Math.abs));
			expect(maxAbsDiff(gram(z, n, k), pyGram), 'gram').toBeLessThanOrEqual(mdsTol(c, gramMax));
			// Within a degenerate eigenspace (the equilateral triangle: two equal eigenvalues) any
			// orthonormal basis is correct and only the Gram matrix is comparable.
			if (c.name !== 'equilateral_3_points_padding') checkMdsColumns(c, z, c.outputs.coords, n, k, gramMax);
		});
	}
});

describe('dataset/rescale_rule.json', () => {
	const cases = loadJson('dataset/rescale_rule.json');
	for (const c of cases) {
		it(c.name, () => {
			// The inputs/ copies of the two files differ from the stored strings only by a final newline.
			expect(readInput(c.inputs.alignment).trim()).toBe(c.inputs.fasta.trim());
			expect(readInput(c.inputs.tree).trim()).toBe(c.inputs.newick.trim());
			const r = loadAlignmentAndTree(c.inputs.fasta, c.inputs.newick);
			expect(r.taxa).toEqual(c.outputs.taxa);
			expect(r.L).toBe(c.outputs.L);
			expect(r.notices.distanceRescaled).toBe(c.outputs.rescaled);
			expect(r.notices.rawDistMax).toBeCloseTo(c.outputs.raw_dist_max, 6);
			expect(maxAbsDiff(r.d, flat(c.outputs.dist_matrix))).toBeLessThanOrEqual(tol(c));
			// And the raw matrix, straight from compute_fast_dist_matrix.
			const tree = extractTree(c.inputs.newick);
			enforceNonzeroBranchLengths(tree, 1e-4);
			expect(maxAbsDiff(computeFastDistMatrix(tree, r.taxa), flat(c.outputs.raw_dist_matrix))).toBeLessThanOrEqual(tol(c));
		});
	}
});

describe('dataset/prune_identical_sequences.json', () => {
	const cases = loadJson('dataset/prune_identical_sequences.json');
	for (const c of cases) {
		it(c.name, () => {
			const r = pruneIdenticalSequences(c.inputs.seq_dict, c.inputs.taxa);
			expect(r.uniqueTaxa).toEqual(c.outputs.unique_taxa);
			expect(Object.fromEntries(r.dupMap)).toEqual(c.outputs.dup_map);
			expect(r.numPruned).toBe(c.outputs.num_pruned);
		});
	}
});

describe('dataset/load_alignment_and_tree_duplicates.json', () => {
	const cases = loadJson('dataset/load_alignment_and_tree_duplicates.json');
	for (const c of cases) {
		it(c.name, () => {
			const r = loadAlignmentAndTree(c.inputs.fasta, c.inputs.newick, {
				pruneDuplicates: c.inputs.prune_duplicates
			});
			expect(r.taxa).toEqual(c.outputs.taxa);
			expect(r.L).toBe(c.outputs.L);
			expect(maxAbsDiff(r.d, flat(c.outputs.dist_matrix))).toBeLessThanOrEqual(tol(c));
			expect(Array.from(r.c)).toEqual(flat(c.outputs.codon_tokens));
			expect(Array.from(r.invariable, (v) => v === 1)).toEqual(c.outputs.is_aa_invariable);
		});
	}
});

describe('dataset/downsample_taxa_faith_pd.json', () => {
	const cases = loadJson('dataset/downsample_taxa_faith_pd.json');
	for (const c of cases) {
		it(c.name, () => {
			const rows = c.inputs.dist_mat;
			const r = downsampleTaxaFaithPd(Float32Array.from(flat(rows)), c.inputs.taxa, c.inputs.max_species);
			expect(r.taxa).toEqual(c.outputs.selected_taxa);
			if (c.outputs.sub_dist_mat) {
				expect(maxAbsDiff(r.distMat, flat(c.outputs.sub_dist_mat))).toBeLessThanOrEqual(tol(c));
			} else {
				const m = r.taxa.length;
				let diag = 0;
				for (let i = 0; i < m; i++) diag += r.distMat[i * m + i];
				expect(diag).toBe(c.outputs.sub_dist_mat_diagonal_check);
			}
		});
	}
});

describe('dataset/load_alignment_and_tree.json', () => {
	const cases = loadJson('dataset/load_alignment_and_tree.json');
	for (const c of cases) {
		it(c.name, () => {
			const r = loadAlignmentAndTree(readExample(c.inputs.alignment), readExample(c.inputs.tree), {
				maxSpecies: c.inputs.max_species,
				pruneDuplicates: c.inputs.prune_duplicates
			});
			const o = c.outputs;
			expect(r.taxa).toEqual(o.taxa);
			expect(r.L).toBe(o.L);
			expect(r.N).toBe(o.N);
			expect(Array.from(r.c)).toEqual(flat(o.codon_tokens));
			expect(Array.from(r.a)).toEqual(flat(o.aa_tokens));
			expect(r.notices.distanceRescaled).toBe(o.rescaled_by_L);
			expect(r.notices.rawDistMax).toBeCloseTo(o.raw_dist_max, 5);
			expect(maxAbsDiff(r.d, flat(o.dist_matrix)), 'dist_matrix').toBeLessThanOrEqual(1e-6);
			// Exact per column, sign included: both sides canonical (inputs.mds_sign), 1e-5 absolute after rescale.
			expect(c.inputs.mds_sign).toBe('canonical');
			expect(maxColumnDiff(r.z, o.mds_coords, r.N, 4), 'mds exact (canonical sign)').toBeLessThanOrEqual(tol(c));
			expect(maxAbsDiff(gram(r.z, r.N, 4), flat(o.mds_gram)), 'mds gram').toBeLessThanOrEqual(tol(c));
			expect(Array.from(r.invariable, (v) => v === 1)).toEqual(o.is_aa_invariable);
			expect(r.invariable.reduce((s, v) => s + v, 0)).toBe(o.n_invariable);
			// The taxa the fixture recorded are what tree order gives.
			expect(treeTaxa(r.tree).filter((t) => r.taxa.includes(t))).toEqual(r.taxa);
		});
	}
});
