/**
 * WHY THIS FILE EXISTS
 *
 * Replays test/data/numeric/special.json (scipy 1.16 reference values, generated by
 * test/data/numeric/gen.py) against src/numeric/special.js. The fixture tolerance class for the
 * special functions is 1e-9 absolute (fixtures/README.md); this holds the primitives to 1e-12
 * RELATIVE so the ports that compose them (mixture nulls, t-tests, patch scans) have three orders of
 * margin, and so a regression in a tail — where 1e-9 absolute would pass anything — is caught.
 *
 * The rule per value: exact for 0, ±Infinity and NaN; otherwise |js − ref| ≤ 1e-12·|ref|, or, when
 * the reference is below 1e-300 (deep denormal tails where scipy itself is only a few digits),
 * |js − ref| ≤ 1e-300. lgamma is checked at its zeros (x = 1, 2) exactly and elsewhere relatively.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import * as special from '../src/numeric/special.js';

const DATA = join(dirname(fileURLToPath(import.meta.url)), 'data', 'numeric');
const ref = JSON.parse(readFileSync(join(DATA, 'special.json'), 'utf8'));

const REL = 1e-12;
const DEEP = 1e-300;

function num(v) {
	if (v === 'NaN') return NaN;
	if (v === 'Infinity') return Infinity;
	if (v === '-Infinity') return -Infinity;
	return v;
}

/** Relative-or-deep-tail closeness, as the header describes. Returns the failure text or null. */
function mismatch(got, want) {
	if (Number.isNaN(want)) return Number.isNaN(got) ? null : `expected NaN, got ${got}`;
	if (!Number.isFinite(want)) return Object.is(got, want) ? null : `expected ${want}, got ${got}`;
	if (want === 0) return got === 0 ? null : `expected exactly 0, got ${got}`;
	const err = Math.abs(got - want);
	if (Math.abs(want) < DEEP) return err <= DEEP ? null : `deep tail: |Δ| = ${err} > ${DEEP}`;
	const rel = err / Math.abs(want);
	return rel <= REL ? null : `rel err ${rel.toExponential(2)} (got ${got}, want ${want})`;
}

describe('special.json replay: scalar special functions vs scipy', () => {
	const byFn = new Map();
	for (const c of ref.cases) {
		if (!byFn.has(c.fn)) byFn.set(c.fn, []);
		byFn.get(c.fn).push(c);
	}

	for (const [fn, cases] of byFn) {
		it(`${fn} (${cases.length} points) within 1e-12 relative`, () => {
			const f = special[fn];
			expect(typeof f, `${fn} exported`).toBe('function');
			const failures = [];
			let worst = 0;
			for (const c of cases) {
				const args = c.args.map(num);
				const want = num(c.value);
				const got = f(...args);
				const m = mismatch(got, want);
				if (m) failures.push(`${fn}(${args.join(', ')}): ${m}`);
				if (Number.isFinite(want) && want !== 0) worst = Math.max(worst, Math.abs(got - want) / Math.abs(want));
			}
			expect(failures, failures.slice(0, 10).join('\n')).toEqual([]);
			expect(worst).toBeLessThanOrEqual(REL);
		});
	}

	it('covers every exported special function', () => {
		const exported = Object.keys(special).filter((k) => typeof special[k] === 'function');
		const covered = new Set([...byFn.keys(), 'hypergeomPmf', 'hypergeomCdf', 'hypergeomSf']);
		for (const name of exported) expect(covered.has(name), `${name} has reference values`).toBe(true);
	});
});

describe('special.json replay: hypergeometric over full supports (scipy argument order k, M, n, N)', () => {
	for (const h of ref.hypergeom) {
		it(`M=${h.M} n=${h.n} N=${h.N}: pmf/cdf/sf on k=${h.k[0]}..${h.k[h.k.length - 1]}`, () => {
			const failures = [];
			h.k.forEach((k, i) => {
				const checks = [
					['pmf', special.hypergeomPmf(k, h.M, h.n, h.N), num(h.pmf[i])],
					['cdf', special.hypergeomCdf(k, h.M, h.n, h.N), num(h.cdf[i])],
					['sf', special.hypergeomSf(k, h.M, h.n, h.N), num(h.sf[i])],
					['1-cdf(k-1)', 1 - special.hypergeomCdf(k - 1, h.M, h.n, h.N), num(h.one_minus_cdf_km1[i])],
				];
				for (const [what, got, want] of checks) {
					// 1 − cdf(k−1) is the filter.py:78 call shape; its cancellation is the Python's own, so the
					// comparison there is absolute at the 1e-9 fixture class, not relative.
					const m = what === '1-cdf(k-1)' ? (Math.abs(got - want) <= 1e-12 ? null : `|Δ| = ${Math.abs(got - want)}`) : mismatch(got, want);
					if (m) failures.push(`${what}(k=${k}): ${m}`);
				}
			});
			expect(failures, failures.slice(0, 10).join('\n')).toEqual([]);
			// Outside the support: pmf 0, cdf exactly 0/1, sf exactly 1/0.
			expect(special.hypergeomPmf(h.lo - 1, h.M, h.n, h.N)).toBe(0);
			expect(special.hypergeomPmf(h.hi + 1, h.M, h.n, h.N)).toBe(0);
			expect(special.hypergeomCdf(h.lo - 1, h.M, h.n, h.N)).toBe(0);
			expect(special.hypergeomCdf(h.hi, h.M, h.n, h.N)).toBe(1);
			expect(special.hypergeomSf(h.lo - 1, h.M, h.n, h.N)).toBe(1);
			expect(special.hypergeomSf(h.hi, h.M, h.n, h.N)).toBe(0);
		});
	}

	it('non-integer k: pmf is 0; cdf and sf are 0/1 outside the support and NaN inside (scipy 1.16)', () => {
		for (const c of ref.hypergeom_noninteger) {
			expect(special.hypergeomPmf(c.k, c.M, c.n, c.N)).toBe(num(c.pmf));
			expect(mismatch(special.hypergeomCdf(c.k, c.M, c.n, c.N), num(c.cdf))).toBeNull();
			expect(mismatch(special.hypergeomSf(c.k, c.M, c.n, c.N), num(c.sf))).toBeNull();
		}
	});

	it('invalid population arguments give NaN', () => {
		expect(special.hypergeomCdf(1, 10, 11, 3)).toBeNaN();
		expect(special.hypergeomPmf(1, 10, 3, 11)).toBeNaN();
		expect(special.hypergeomSf(1, 10.5, 3, 2)).toBeNaN();
	});
});

describe('identities and domain edges the grid does not pin', () => {
	it('P + Q = 1 across the a/x grid', () => {
		for (const a of [0.5, 1, 1.5, 2, 7, 10, 42, 100, 1000]) {
			for (const x of [1e-6, 0.01, 0.5, 1, 3, 9, 11, 40, 99, 101, 400, 1500]) {
				expect(special.gammaincReg(a, x) + special.gammaincc(a, x)).toBeCloseTo(1, 14);
			}
		}
	});

	it('I_x(a,b) + I_{1-x}(b,a) = 1 and the boundary values are exact', () => {
		for (const a of [0.5, 1, 3, 10, 100])
			for (const b of [0.5, 2, 10, 500])
				for (const x of [0.001, 0.2, 0.5, 0.8, 0.999]) {
					expect(special.betaincReg(a, b, x) + special.betaincReg(b, a, 1 - x)).toBeCloseTo(1, 14);
				}
		expect(special.betaincReg(2, 3, 0)).toBe(0);
		expect(special.betaincReg(2, 3, 1)).toBe(1);
		expect(special.betaincReg(2, 3, 1.5)).toBeNaN();
		expect(special.betaincReg(0, 3, 0.5)).toBeNaN();
	});

	it('chi2Sf(x, 2) is exp(-x/2) and tSf(t, 1) is the Cauchy tail', () => {
		for (const x of [0.1, 1, 3.84, 20, 75, 120, 700]) {
			expect(mismatch(special.chi2Sf(x, 2), Math.exp(-x / 2))).toBeNull();
		}
		for (const t of [0.1, 1, 5, 40]) {
			expect(mismatch(special.tSf(t, 1), 0.5 - Math.atan(t) / Math.PI)).toBeNull();
		}
	});

	it('normSf(z) + normCdf(z) = 1, and normSf(z) = normCdf(-z)', () => {
		for (const z of [-8, -3, -1, 0, 0.3, 1, 2.5, 6, 30]) {
			expect(special.normSf(z) + special.normCdf(z)).toBeCloseTo(1, 15);
			expect(special.normSf(z)).toBe(special.normCdf(-z));
		}
	});

	it('lgamma reproduces the zeros and poles', () => {
		expect(special.lgamma(1)).toBe(0);
		expect(special.lgamma(2)).toBe(0);
		expect(special.lgamma(0)).toBe(Infinity);
		expect(special.lgamma(-3)).toBe(Infinity);
		expect(special.lgamma(NaN)).toBeNaN();
		expect(special.lgamma(0.5)).toBeCloseTo(Math.log(Math.sqrt(Math.PI)), 15);
	});

	it('logChoose agrees between the exact integer path and the gamma path', () => {
		expect(special.logChoose(70, 64)).toBeCloseTo(special.lgamma(71) - special.lgamma(65) - special.lgamma(7), 12);
		expect(special.logChoose(10, 0)).toBe(0);
		expect(special.logChoose(10, 10)).toBe(0);
		expect(special.logChoose(3, 4)).toBe(-Infinity);
		expect(special.logChoose(3, -1)).toBe(-Infinity);
	});
});
