/**
 * WHY THIS FILE EXISTS
 *
 * Replays fixtures/stats/benjamini_hochberg.json and fixtures/stats/cauchy_combination_p.json
 * (generated by scripts/gen_fixtures.py from hyphaeon/stats.py:50-84) against src/numeric/bh.js and
 * src/numeric/cauchy.js. These are the first two fixtures after the tokenizer to be replayed as a
 * plain pass (fixtures.test.js pins the manifest; this pins the numbers).
 *
 * DTYPE IS PART OF THE CASE. Two cases were generated from float32 arrays (`float32_meme_like`,
 * `float32_input`) and the Python did float32 arithmetic on them (see bh.js and cauchy.js headers;
 * measured differences 4.2e-8 and 9e-8 against a float64 replay, both above the 1e-9 class). The
 * generator records `inputs.dtype: "float32"` on those cases (gen_fixtures.py `with_dtype`; float64
 * cases carry no dtype key), and that key, not the case name, selects the Float32Array replay.
 *
 * Tolerance: the fixture class is 1e-9 absolute; the assertion here is that AND a tighter 1e-14
 * check on the float64 cases, since BH is in PLAN.md §5.4's exact class.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { benjaminiHochberg } from '../src/numeric/bh.js';
import { cauchyCombination } from '../src/numeric/cauchy.js';

const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'fixtures', 'stats');

function load(name) {
	return JSON.parse(readFileSync(join(FIXTURES, name), 'utf8'));
}

const isFloat32 = (c) => c.inputs.dtype === 'float32';

function inputArray(c) {
	return isFloat32(c) ? Float32Array.from(c.inputs.pvals) : Float64Array.from(c.inputs.pvals);
}

describe('fixtures/stats/benjamini_hochberg.json replay (hyphaeon/stats.py:50-70)', () => {
	const cases = load('benjamini_hochberg.json');

	it('has the eleven cases the manifest records', () => {
		expect(cases.map((c) => c.name)).toEqual([
			'empty', 'single', 'single_one', 'all_ones', 'all_zeros', 'ties', 'monotone_step',
			'with_p_equal_one_and_zero', 'random_uniform_100', 'float32_meme_like', 'clip_above_one',
		]);
	});

	for (const c of cases) {
		it(`${c.name} (n=${c.inputs.pvals.length}, ${c.tolerance})`, () => {
			expect(c.tolerance).toBe('1e-9');
			const got = benjaminiHochberg(inputArray(c));
			expect(got).toBeInstanceOf(Float64Array);
			expect(got.length).toBe(c.outputs.qvals.length);
			const tight = isFloat32(c) ? 1e-9 : 1e-14;
			c.outputs.qvals.forEach((want, i) => {
				expect(Math.abs(got[i] - want), `q[${i}]`).toBeLessThanOrEqual(tight);
			});
		});
	}

	it('float32 input is what makes float32_meme_like match: a float64 replay is off by ~4e-8', () => {
		const c = cases.find((x) => x.name === 'float32_meme_like');
		const f64 = benjaminiHochberg(Float64Array.from(c.inputs.pvals));
		let maxDiff = 0;
		c.outputs.qvals.forEach((want, i) => {
			maxDiff = Math.max(maxDiff, Math.abs(f64[i] - want));
		});
		expect(maxDiff).toBeGreaterThan(1e-9);
		expect(maxDiff).toBeLessThan(1e-7);
	});

	it('plain arrays work and the result is clipped to [0, 1]', () => {
		expect(Array.from(benjaminiHochberg([0.9, 0.95, 1.0, 0.3]))).toEqual([1, 1, 1, 1]);
		expect(Array.from(benjaminiHochberg([0.02, 0.01]))).toEqual([0.02, 0.02]);
	});
});

describe('fixtures/stats/cauchy_combination_p.json replay (hyphaeon/stats.py:72-84)', () => {
	const cases = load('cauchy_combination_p.json');

	it('has the twelve cases the manifest records', () => {
		expect(cases).toHaveLength(12);
	});

	for (const c of cases) {
		it(`${c.name} (n=${c.inputs.pvals.length}, ${c.tolerance})`, () => {
			expect(c.tolerance).toBe('1e-9');
			const got = cauchyCombination(inputArray(c));
			const want = c.outputs.p_cct;
			const tight = isFloat32(c) ? 1e-9 : 1e-14;
			expect(Math.abs(got - want), `got ${got} want ${want}`).toBeLessThanOrEqual(tight);
		});
	}

	it('float32 input is what makes float32_input match: a float64 replay is off by ~9e-8', () => {
		const c = cases.find((x) => x.name === 'float32_input');
		const diff = Math.abs(cauchyCombination(Float64Array.from(c.inputs.pvals)) - c.outputs.p_cct);
		expect(diff).toBeGreaterThan(1e-9);
		expect(diff).toBeLessThan(1e-6);
	});

	it('clips at both ends exactly as np.clip does', () => {
		expect(cauchyCombination([])).toBe(1.0);
		expect(cauchyCombination([0, 0])).toBe(1e-15);
		expect(cauchyCombination([1])).toBe(0.999999999999999);
	});
});
