/**
 * WHY THIS FILE EXISTS
 *
 * Replays test/data/numeric/special.json (scipy 1.16 reference values, generated by
 * test/data/numeric/gen.py) against src/numeric/special.js. The fixture tolerance class for the
 * special functions is 1e-9 absolute (fixtures/README.md); this holds the primitives to 1e-12
 * RELATIVE so the ports that compose them (mixture nulls, t-tests, patch scans) have three orders of
 * margin, and so a regression in a tail — where 1e-9 absolute would pass anything — is caught.
 *
 * The rule per value: exact for 0, ±Infinity and NaN; otherwise |js − ref| ≤ 1e-12·|ref|, or, when
 * the reference is below 1e-300 (deep denormal tails where scipy itself is only a few digits),
 * |js − ref| ≤ 1e-300. lgamma is checked at its zeros (x = 1, 2) exactly and elsewhere relatively.
 *
 * TWO FUNCTIONS ARE NOT MEASURED AGAINST SCIPY, and saying so is the point:
 *
 *   - `tPpf` is held to 1e-13 relative against MPMATH at 40 dps, because scipy's own `t.ppf` is the
 *     less accurate of the two: cephes `stdtri` polishes with a loose stopping rule and is off by
 *     up to 3.7e-11 relative on this grid (worst at df = 100, q = 0.975), and it returns ~7e-17
 *     rather than 0 at q = 0.5 for every df. gen.py arbitrates with mpmath and writes the mpmath
 *     value wherever the two disagree by more than 1e-13, recording every such point under
 *     `scipy_deviations` — the same mechanism `betaincReg` already uses. A test that claimed
 *     agreement with scipy to 1e-12 here would be a false claim and would fail on the first run.
 *   - `1 − fCdf` is the call shape dating.py:1269 uses where `f.sf` was meant, and it is compared
 *     at 1e-12 relative OR 1e-15 absolute, whichever is looser: the subtraction quantises at one ulp
 *     of 1.0, and scipy's own cdf is one ulp BELOW 1 at F = 194.58 / dfd = 93 (the H1N1 fit's own
 *     value) where the correctly rounded double is exactly 1.0. `one_minus_f_cdf` carries both
 *     spellings side by side, from mpmath, so the size of the upstream defect is in the record
 *     rather than in a comment.
 *
 * `fSf` and `fCdf` are arbitrated by mpmath for the same reason `tPpf` is: MEASURED,
 * `scipy.stats.f.sf(1e-12, 1, 139)` is 4.9e-9 relative from the truth (Boost's ibeta at an x within
 * 1e-14 of 1), while this file's incomplete beta reproduces mpmath to 17 digits there.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import * as special from '../src/numeric/special.js';

const DATA = join(dirname(fileURLToPath(import.meta.url)), 'data', 'numeric');
const ref = JSON.parse(readFileSync(join(DATA, 'special.json'), 'utf8'));

const REL = 1e-12;
const DEEP = 1e-300;
/** Per-function bounds tighter or looser than the house 1e-12; see the header. */
const REL_BY_FN = { tPpf: 1e-13 };

function num(v) {
	if (v === 'NaN') return NaN;
	if (v === 'Infinity') return Infinity;
	if (v === '-Infinity') return -Infinity;
	return v;
}

/** Relative-or-deep-tail closeness, as the header describes. Returns the failure text or null. */
function mismatch(got, want, bound = REL) {
	if (Number.isNaN(want)) return Number.isNaN(got) ? null : `expected NaN, got ${got}`;
	if (!Number.isFinite(want)) return Object.is(got, want) ? null : `expected ${want}, got ${got}`;
	if (want === 0) return got === 0 ? null : `expected exactly 0, got ${got}`;
	const err = Math.abs(got - want);
	if (Math.abs(want) < DEEP) return err <= DEEP ? null : `deep tail: |Δ| = ${err} > ${DEEP}`;
	const rel = err / Math.abs(want);
	return rel <= bound ? null : `rel err ${rel.toExponential(2)} (got ${got}, want ${want})`;
}

describe('special.json replay: scalar special functions vs scipy', () => {
	const byFn = new Map();
	for (const c of ref.cases) {
		if (!byFn.has(c.fn)) byFn.set(c.fn, []);
		byFn.get(c.fn).push(c);
	}

	for (const [fn, cases] of byFn) {
		const bound = REL_BY_FN[fn] ?? REL;
		it(`${fn} (${cases.length} points) within ${bound} relative`, () => {
			const f = special[fn];
			expect(typeof f, `${fn} exported`).toBe('function');
			const failures = [];
			let worst = 0;
			for (const c of cases) {
				const args = c.args.map(num);
				const want = num(c.value);
				const got = f(...args);
				const m = mismatch(got, want, bound);
				if (m) failures.push(`${fn}(${args.join(', ')}): ${m}`);
				if (Number.isFinite(want) && want !== 0) worst = Math.max(worst, Math.abs(got - want) / Math.abs(want));
			}
			expect(failures, failures.slice(0, 10).join('\n')).toEqual([]);
			expect(worst).toBeLessThanOrEqual(bound);
		});
	}

	it('scipy itself is the outlier at tPpf: the recorded deviations are real and mpmath is the arbiter', () => {
		const dev = ref.scipy_deviations.filter((d) => d.fn === 'tPpf');
		expect(dev.length, 'gen.py recorded scipy/mpmath disagreements for tPpf').toBeGreaterThan(0);
		let worstScipy = 0;
		for (const d of dev) {
			if (d.rel === 'Infinity') {
				// q = 0.5: scipy returns ~7e-17, the port returns exact 0.
				expect(Math.abs(d.scipy)).toBeLessThan(1e-16);
				expect(special.tPpf(d.args[0], d.args[1])).toBe(0);
				continue;
			}
			worstScipy = Math.max(worstScipy, d.rel);
			// The port is closer to mpmath than scipy is, at every recorded point.
			const got = special.tPpf(d.args[0], d.args[1]);
			expect(Math.abs(got - d.mpmath), `tPpf(${d.args.join(', ')})`).toBeLessThan(Math.abs(d.scipy - d.mpmath));
		}
		// MEASURED at this fixture: 3.73e-11 relative, at df = 100, q = 0.975.
		expect(worstScipy).toBeGreaterThan(1e-11);
	});

	it("dating.py:1269's `1 - f.cdf` spelling, and the size of what it loses", () => {
		let worstLoss = 0;
		for (const row of ref.one_minus_f_cdf) {
			const [x, dfn, dfd] = row.args;
			const got = 1 - special.fCdf(x, dfn, dfd);
			const want = num(row.one_minus_cdf);
			// Relative at the house bound where the value carries digits, absolute at 1e-15 where the
			// subtraction has quantised it to a multiple of one ulp of 1.0 and there are none left.
			const bound = Math.max(1e-15, REL * Math.abs(want));
			expect(Math.abs(got - want), `1 - fCdf(${row.args.join(', ')})`).toBeLessThanOrEqual(bound);
			const sf = num(row.sf);
			if (sf > 0 && want === 0) {
				// `1 - cdf` has annihilated a real probability: the whole tail is below one ulp of 1.
				worstLoss++;
				expect(1 - special.fCdf(x, dfn, dfd), `1 - fCdf(${row.args.join(', ')}) annihilates`).toBe(0);
				expect(special.fSf(x, dfn, dfd), `fSf(${row.args.join(', ')}) does not`).toBeGreaterThan(0);
			}
		}
		// The defect is not hypothetical. MEASURED on this grid: from F ≈ 80 upward the true
		// `1 − cdf` is exactly 0 in float64 while the survival function is still 1e-15 to 1e-25, and
		// scipy's own cdf hides that by returning one ulp below 1 (H1N1's run reports 1.11e-16 for a
		// p-value whose real value is 1.59e-24). The port replicates the reference's spelling and the
		// annihilation with it.
		expect(worstLoss, 'rows where `1 - cdf` annihilates a tail `sf` still resolves').toBeGreaterThan(5);
	});

	it('covers every exported special function', () => {
		const exported = Object.keys(special).filter((k) => typeof special[k] === 'function');
		const covered = new Set([...byFn.keys(), 'hypergeomPmf', 'hypergeomCdf', 'hypergeomSf']);
		for (const name of exported) expect(covered.has(name), `${name} has reference values`).toBe(true);
	});
});

describe('special.json replay: hypergeometric over full supports (scipy argument order k, M, n, N)', () => {
	for (const h of ref.hypergeom) {
		it(`M=${h.M} n=${h.n} N=${h.N}: pmf/cdf/sf on k=${h.k[0]}..${h.k[h.k.length - 1]}`, () => {
			const failures = [];
			h.k.forEach((k, i) => {
				const checks = [
					['pmf', special.hypergeomPmf(k, h.M, h.n, h.N), num(h.pmf[i])],
					['cdf', special.hypergeomCdf(k, h.M, h.n, h.N), num(h.cdf[i])],
					['sf', special.hypergeomSf(k, h.M, h.n, h.N), num(h.sf[i])],
					['1-cdf(k-1)', 1 - special.hypergeomCdf(k - 1, h.M, h.n, h.N), num(h.one_minus_cdf_km1[i])],
				];
				for (const [what, got, want] of checks) {
					// 1 − cdf(k−1) is the filter.py:78 call shape; its cancellation is the Python's own, so the
					// comparison there is absolute at the 1e-9 fixture class, not relative.
					const m = what === '1-cdf(k-1)' ? (Math.abs(got - want) <= 1e-12 ? null : `|Δ| = ${Math.abs(got - want)}`) : mismatch(got, want);
					if (m) failures.push(`${what}(k=${k}): ${m}`);
				}
			});
			expect(failures, failures.slice(0, 10).join('\n')).toEqual([]);
			// Outside the support: pmf 0, cdf exactly 0/1, sf exactly 1/0.
			expect(special.hypergeomPmf(h.lo - 1, h.M, h.n, h.N)).toBe(0);
			expect(special.hypergeomPmf(h.hi + 1, h.M, h.n, h.N)).toBe(0);
			expect(special.hypergeomCdf(h.lo - 1, h.M, h.n, h.N)).toBe(0);
			expect(special.hypergeomCdf(h.hi, h.M, h.n, h.N)).toBe(1);
			expect(special.hypergeomSf(h.lo - 1, h.M, h.n, h.N)).toBe(1);
			expect(special.hypergeomSf(h.hi, h.M, h.n, h.N)).toBe(0);
		});
	}

	it('non-integer k: pmf is 0; cdf and sf are 0/1 outside the support and NaN inside (scipy 1.16)', () => {
		for (const c of ref.hypergeom_noninteger) {
			expect(special.hypergeomPmf(c.k, c.M, c.n, c.N)).toBe(num(c.pmf));
			expect(mismatch(special.hypergeomCdf(c.k, c.M, c.n, c.N), num(c.cdf))).toBeNull();
			expect(mismatch(special.hypergeomSf(c.k, c.M, c.n, c.N), num(c.sf))).toBeNull();
		}
	});

	it('invalid population arguments give NaN', () => {
		expect(special.hypergeomCdf(1, 10, 11, 3)).toBeNaN();
		expect(special.hypergeomPmf(1, 10, 3, 11)).toBeNaN();
		expect(special.hypergeomSf(1, 10.5, 3, 2)).toBeNaN();
	});
});

describe('identities and domain edges the grid does not pin', () => {
	it('P + Q = 1 across the a/x grid', () => {
		for (const a of [0.5, 1, 1.5, 2, 7, 10, 42, 100, 1000]) {
			for (const x of [1e-6, 0.01, 0.5, 1, 3, 9, 11, 40, 99, 101, 400, 1500]) {
				expect(special.gammaincReg(a, x) + special.gammaincc(a, x)).toBeCloseTo(1, 14);
			}
		}
	});

	it('I_x(a,b) + I_{1-x}(b,a) = 1 and the boundary values are exact', () => {
		for (const a of [0.5, 1, 3, 10, 100])
			for (const b of [0.5, 2, 10, 500])
				for (const x of [0.001, 0.2, 0.5, 0.8, 0.999]) {
					expect(special.betaincReg(a, b, x) + special.betaincReg(b, a, 1 - x)).toBeCloseTo(1, 14);
				}
		expect(special.betaincReg(2, 3, 0)).toBe(0);
		expect(special.betaincReg(2, 3, 1)).toBe(1);
		expect(special.betaincReg(2, 3, 1.5)).toBeNaN();
		expect(special.betaincReg(0, 3, 0.5)).toBeNaN();
	});

	it('chi2Sf(x, 2) is exp(-x/2) and tSf(t, 1) is the Cauchy tail', () => {
		for (const x of [0.1, 1, 3.84, 20, 75, 120, 700]) {
			expect(mismatch(special.chi2Sf(x, 2), Math.exp(-x / 2))).toBeNull();
		}
		for (const t of [0.1, 1, 5, 40]) {
			expect(mismatch(special.tSf(t, 1), 0.5 - Math.atan(t) / Math.PI)).toBeNull();
		}
	});

	it('normSf(z) + normCdf(z) = 1, and normSf(z) = normCdf(-z)', () => {
		for (const z of [-8, -3, -1, 0, 0.3, 1, 2.5, 6, 30]) {
			expect(special.normSf(z) + special.normCdf(z)).toBeCloseTo(1, 15);
			expect(special.normSf(z)).toBe(special.normCdf(-z));
		}
	});

	it('lgamma reproduces the zeros and poles', () => {
		expect(special.lgamma(1)).toBe(0);
		expect(special.lgamma(2)).toBe(0);
		expect(special.lgamma(0)).toBe(Infinity);
		expect(special.lgamma(-3)).toBe(Infinity);
		expect(special.lgamma(NaN)).toBeNaN();
		expect(special.lgamma(0.5)).toBeCloseTo(Math.log(Math.sqrt(Math.PI)), 15);
	});

	it('logChoose agrees between the exact integer path and the gamma path', () => {
		expect(special.logChoose(70, 64)).toBeCloseTo(special.lgamma(71) - special.lgamma(65) - special.lgamma(7), 12);
		expect(special.logChoose(10, 0)).toBe(0);
		expect(special.logChoose(10, 10)).toBe(0);
		expect(special.logChoose(3, 4)).toBe(-Infinity);
		expect(special.logChoose(3, -1)).toBe(-Infinity);
	});
});
