/**
 * WHY THIS FILE EXISTS
 *
 * Replays test/data/sectors/graph.json (networkx 3.6.1 under CPython 3.14, see gen.py) against
 * src/numeric/graph.js: CPython set iteration order, the subgraph view's node and neighbour order,
 * connected_components order, and greedy_modularity_communities on ~400 graphs — random weighted,
 * integer-weighted (ties), unweighted, complete/cycle/path/star (every merge ties), two cliques with
 * a bridge, disconnected (the StopIteration path), cutoff / best_n / resolution, and induced
 * subgraphs of a 1,097-node graph, the shape epistasis.py hands networkx. Everything here is exact:
 * ordering and membership are the specification.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
	cpythonIntSetOrder,
	adjacencyFromGraph,
	inducedSubgraph,
	connectedComponents,
	greedyModularityCommunities,
	numberOfEdges,
	degree,
	graphSize
} from '../src/numeric/graph.js';

const DATA = join(dirname(fileURLToPath(import.meta.url)), 'data', 'sectors');
const ref = JSON.parse(readFileSync(join(DATA, 'graph.json'), 'utf8'));

/** nodes 1..L in insertion order plus the recorded edges — the epistasis.py graph shape. */
function bigGraph(L, edges) {
	const nodes = Array.from({ length: L }, (_, i) => i + 1);
	return adjacencyFromGraph({ nodes, edges });
}

describe('graph.json provenance', () => {
	it('was generated by networkx 3.6.1 on CPython 3.14', () => {
		expect(ref.networkx).toBe('3.6.1');
		expect(ref.python.startsWith('3.14')).toBe(true);
	});
});

describe('cpythonIntSetOrder', () => {
	it(`matches list(set(values)) on ${ref.set_order.length} lists`, () => {
		for (const c of ref.set_order) expect(cpythonIntSetOrder(c.values)).toEqual(c.order);
	});
	it('falls back to distinct insertion order for non-integer labels', () => {
		expect(cpythonIntSetOrder(['b', 'a', 'b'])).toEqual(['b', 'a']);
		expect(cpythonIntSetOrder([3, -1, 3])).toEqual([3, -1]);
	});
});

describe('adjacencyFromGraph', () => {
	it('appends unknown endpoints in add_edge order and shares one attribute object per edge', () => {
		const adj = adjacencyFromGraph({ nodes: [5], edges: [[2, 1, { weight: 0.5 }], [1, 5, {}], [2, 1, { cesi: 3 }]] });
		expect([...adj.keys()]).toEqual([5, 2, 1]);
		expect(adj.get(2).get(1)).toBe(adj.get(1).get(2));
		expect(adj.get(2).get(1)).toEqual({ weight: 0.5, cesi: 3 });
		expect(numberOfEdges(adj)).toBe(2);
		expect(degree(adj, 1)).toBe(2);
		expect(degree(adj, 1, 'weight')).toBe(1.5); // missing weight reads as 1
		expect(graphSize(adj, 'weight')).toBe(1.5);
	});
});

describe('inducedSubgraph iteration order (FilterAtlas rule)', () => {
	it(`matches list(G.subgraph(nodes)) and list(H[n]) on ${ref.subgraph_order.cases.length} cases`, () => {
		for (const c of ref.subgraph_order.cases) {
			const adj = bigGraph(c.L, ref.subgraph_order.graphs[String(c.L)]);
			const sub = inducedSubgraph(adj, c.nodes);
			expect([...sub.keys()], `L=${c.L} k=${c.nodes.length}`).toEqual(c.node_order);
			for (const n of sub.keys()) {
				expect([...sub.get(n).keys()], `L=${c.L} neighbours of ${n}`).toEqual(c.neighbor_order[String(n)]);
			}
		}
	});
});

describe('connectedComponents', () => {
	it(`matches nx.connected_components order and set order on ${ref.components.cases.length} graphs`, () => {
		for (const c of ref.components.cases) {
			const adj = c.graph ? adjacencyFromGraph(c.graph) : inducedSubgraph(bigGraph(c.L, ref.components.big_edges), c.nodes);
			expect(connectedComponents(adj)).toEqual(c.components);
		}
	});
});

describe('greedyModularityCommunities', () => {
	const groups = new Map();
	for (const c of ref.communities) {
		const g = c.name.replace(/_\d+$/, '');
		if (!groups.has(g)) groups.set(g, []);
		groups.get(g).push(c);
	}
	for (const [group, cases] of groups) {
		it(`${group}: matches networkx on ${cases.length} graph(s)`, () => {
			for (const c of cases) {
				const adj = c.graph ? adjacencyFromGraph(c.graph) : inducedSubgraph(bigGraph(c.L, c.edges), c.sub_nodes);
				const kw = c.kwargs;
				const got = greedyModularityCommunities(adj, {
					weight: kw.weight ?? null,
					resolution: kw.resolution,
					cutoff: kw.cutoff,
					bestN: kw.best_n
				});
				expect(got, c.name).toEqual(c.communities);
			}
		});
	}

	it('returns singletons for an edgeless graph and validates cutoff / best_n', () => {
		const adj = adjacencyFromGraph({ nodes: [3, 1, 2], edges: [] });
		expect(greedyModularityCommunities(adj)).toEqual([[3], [1], [2]]);
		const tri = adjacencyFromGraph({ edges: [[1, 2, {}], [2, 3, {}]] });
		expect(() => greedyModularityCommunities(tri, { cutoff: 0 })).toThrow(RangeError);
		expect(() => greedyModularityCommunities(tri, { bestN: 4 })).toThrow(RangeError);
		expect(() => greedyModularityCommunities(tri, { cutoff: 2, bestN: 1 })).toThrow(RangeError);
		expect(greedyModularityCommunities(tri, { bestN: 1 })).toEqual([[1, 2, 3]]);
	});
});
