/**
 * WHY THIS FILE EXISTS
 *
 * Replays test/data/numeric/optimize.json — scipy.optimize.brentq and numpy.percentile reference
 * values, generated by test/data/numeric/gen.py — against src/numeric/optimize.js and
 * src/numeric/reduce.js. Neither primitive has a hyphaeon body behind it, so neither belongs in
 * fixtures/ (which mirrors hyphaeon functions); test/data/numeric/ is where the scipy/numpy
 * primitives are pinned, as that generator's own header says.
 *
 * WHY THESE TWO ARE HELD TO DIFFERENT BARS.
 *
 *   - `percentile` is EXACT. hyphaeon/dating.py:1844 chooses the restricted cubic spline's second
 *     and third knots as `np.median(times)` and `np.percentile(times, 90)`, and a knot that moves
 *     by one ulp changes every spline number downstream of it — the F statistic, its p-value, ΔAIC
 *     and therefore which clock model is selected and which column of the per-taxon table the
 *     reader is shown. There is nothing here for a tolerance to absorb: the virtual index is
 *     arithmetic on n and q, and the interpolation is numpy's own two-branch `_lerp`.
 *
 *   - `brentq` is held to 1e-10 ABSOLUTE on the root and no tighter, because scipy's own default
 *     `xtol` is 2e-12 and the root is only ever located to that. Demanding less would be theatre.
 *     MEASURED, for the record: this transcription run over all 142 korber taxa through the
 *     reference's fitted spline reproduced the reference's `predicted_date` column to a worst
 *     2.5e-11 years — 0.8 milliseconds — and reproduced its branch counts exactly (118 solved,
 *     12 on the linear arm, 12 with the bracket refused).
 *
 * THE REFUSALS ARE ASSERTED, NOT TOLERATED. dating.py:3024 wraps the call in a bare
 * `except Exception` and substitutes a different model's answer for the rows that raise — on the
 * flagship example that is 12 of 142 rows, with nothing in the JSON or the CSV saying which. A port
 * that returned NaN instead of throwing, or that widened the bracket "to help", would silently
 * change those twelve dates, so the throw is part of the contract and has its own cases here.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { BRENTQ_MAXITER, BRENTQ_RTOL, BRENTQ_XTOL, brentq } from '../src/numeric/optimize.js';
import { percentile } from '../src/numeric/reduce.js';

const DATA = join(dirname(fileURLToPath(import.meta.url)), 'data', 'numeric');
const ref = JSON.parse(readFileSync(join(DATA, 'optimize.json'), 'utf8'));

/** The closures gen.py used, by name. Kept here rather than eval'd, and checked by the root. */
const FUNCTIONS = {
	cubic: (x) => x ** 3 - 2 * x - 5,
	flat_near_root: (x) => (x - 1.0) ** 3,
	steep: (x) => Math.exp(x) - 1e6,
	root_at_a: (x) => x - 1.0,
	root_at_b: (x) => x - 3.0,
	shallow_wide: (x) => 1e-14 * (x - 1234.5),
	negative_bracket: (x) => Math.cos(x) - x,
	same_sign_positive: (x) => x * x + 1.0,
	same_sign_both_negative: (x) => x - 10.0,
};

describe('brentq: scipy.optimize.brentq, transcribed from Zeros/brentq.c', () => {
	it("the defaults are scipy's own", () => {
		expect(BRENTQ_XTOL).toBe(ref.brentq_defaults.xtol);
		expect(BRENTQ_RTOL).toBe(ref.brentq_defaults.rtol);
		expect(BRENTQ_MAXITER).toBe(ref.brentq_defaults.maxiter);
	});

	for (const c of ref.brentq) {
		it(`${c.name}: root within 1e-10 of scipy's (${c.notes})`, () => {
			const f = FUNCTIONS[c.name];
			expect(typeof f, `${c.name} has a closure`).toBe('function');
			const got = brentq(f, c.a, c.b);
			expect(got.converged, 'converged inside maxiter').toBe(true);
			expect(Math.abs(got.x - c.root), `${c.name}: got ${got.x}, scipy ${c.root}`).toBeLessThanOrEqual(1e-10);
			// And the answer is a root of the function, not merely close to scipy's answer.
			const scale = Math.max(1, Math.abs(c.b - c.a));
			expect(Math.abs(f(got.x))).toBeLessThanOrEqual(Math.max(1e-9, 1e-9 * Math.abs(f(c.a) - f(c.b))) * scale);
		});
	}

	for (const c of ref.brentq_refusals) {
		it(`${c.name}: throws where scipy raises ValueError (${c.notes})`, () => {
			const f = FUNCTIONS[c.name];
			expect(() => brentq(f, c.a, c.b)).toThrow(RangeError);
			expect(c.error).toMatch(/different signs/);
		});
	}

	it('a zero at either end returns immediately, before any iteration', () => {
		expect(brentq((x) => x - 1, 1, 3)).toMatchObject({ x: 1, iterations: 0, converged: true });
		expect(brentq((x) => x - 3, 1, 3)).toMatchObject({ x: 3, iterations: 0, converged: true });
	});

	it('maxIter is honoured and reports a failure to converge rather than looping', () => {
		const got = brentq((x) => x ** 3 - 2 * x - 5, 2, 3, { maxIter: 1, xtol: 1e-300, rtol: 2.3e-16 });
		expect(got.converged).toBe(false);
		expect(got.iterations).toBe(1);
	});

	it('xtol and rtol widen the stopping rule, as scipy documents', () => {
		const tight = brentq((x) => x ** 3 - 2 * x - 5, 2, 3);
		const loose = brentq((x) => x ** 3 - 2 * x - 5, 2, 3, { xtol: 1e-3 });
		expect(loose.functionCalls).toBeLessThanOrEqual(tight.functionCalls);
		expect(Math.abs(loose.x - tight.x)).toBeLessThanOrEqual(1e-3);
	});
});

describe('percentile: numpy 2.3 method "linear", in float64', () => {
	for (const c of ref.percentile) {
		it(`${c.label} q=${c.q}: bit-identical to numpy`, () => {
			expect(percentile(c.x, c.q)).toBe(c.value);
		});
	}

	it('percentile(x, 50) IS np.median, for odd and even n alike — no separate median is needed', () => {
		for (const c of ref.percentile) expect(percentile(c.x, 50)).toBe(c.median);
	});

	it('does not mutate its input, and answers the degenerate shapes', () => {
		const x = [3, 1, 2];
		expect(percentile(x, 50)).toBe(2);
		expect(x).toEqual([3, 1, 2]);
		expect(percentile([], 50)).toBeNaN();
		expect(percentile([1, NaN, 3], 50)).toBeNaN();
		expect(percentile([7], 0)).toBe(7);
		expect(percentile([7], 100)).toBe(7);
	});
});
