/**
 * omnibus.test.js — the BUSTED statistical bridge of cli.py cmd_busted (src/omnibus.js).
 *
 * WHY THIS FILE EXISTS
 *
 * Three oracles, from strongest to weakest:
 *   1. fixtures/e2e/busted_Smc6.json and busted_HIV1_RT.json — the CLI's own JSON. They carry the
 *      aggregate statistics but NOT the per-site LRTs they were computed from; those are taken from
 *      fixtures/e2e/meme_Smc6.json / meme_HIV1_RT.json, whose `sites[].hyphaeon_lrt` the same
 *      model produced on the same taxa (cmd_meme and cmd_busted both run `forward_cached` on the
 *      variable sites and clamp at 0). That the meme LRTs reproduce every busted statistic bit for
 *      bit was verified with the reference Python before this test was written, so the replay is a
 *      test of the JS arithmetic, not of that assumption. The neural-head fields are null in the
 *      fixtures (the reference head is non-deterministic, fixtures/README.md) and are asserted
 *      null here.
 *   2. test/data/omnibus/busted_stats.json — the same cli.py lines on seeded random and edge-case
 *      inputs (no variable sites, one site, LRTs at the 3.841 threshold, huge LRTs, ties,
 *      denormals), generated by test/data/omnibus/gen.py with numpy 2.3.3.
 *   3. Hand-checkable unit cases for each exported function, and a fake-model exercise of
 *      `runBusted` that pins the loop's contract: variable sites only, ascending, batched, clamped,
 *      `hidden_all` zero at invariable sites, an all-false mask to the head.
 *
 * TOLERANCES. The float32 sums (`total_selection_energy`, `omnibus_lrt`) are asserted EQUAL: the
 * reference is a float32 pairwise reduction and omnibus.js reproduces it (a float64 sum is shown to
 * miss by ~6e-6, which the fixture's 1e-5 class would hide). The float64 p-values are asserted to
 * 1e-12 (fixture class 1e-9 for float64 statistics); counts exactly.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
	BUSTED_OMEGA_1,
	BUSTED_OMEGA_2,
	BUSTED_LRT_THRESHOLD,
	BUSTED_EMBED_DIM,
	BUSTED_HEAD_INPUT_NAMES,
	BUSTED_HEAD_OUTPUT_NAMES,
	variableSiteIndices,
	totalSelectionEnergy,
	omnibusLrt,
	simesP,
	bustedStatistics,
	bustedHeadFields,
	bustedVerdict,
	bustedRecord,
	gatherSiteBatch,
	runBusted
} from '../src/omnibus.js';
import { float32Sum } from '../src/numeric/reduce.js';
import { loadAlignmentAndTree, siteBatch } from '../src/preprocess/assemble.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(HERE, '..', '..', 'fixtures');
const loadFixture = (rel) => JSON.parse(readFileSync(join(FIXTURES, rel), 'utf8'));
const LOCAL = JSON.parse(readFileSync(join(HERE, 'data', 'omnibus', 'busted_stats.json'), 'utf8'));

/** The record keys of cmd_busted's JSON, in order (cli.py:486-505). */
const RECORD_KEYS = [
	'alignment', 'gene', 'taxa', 'sites', 'p_value_acat', 'p_value_simes', 'omnibus_lrt',
	'predicted_gene_lrt', 'selection_probability', 'synonymous_rate_variation',
	'total_selection_energy', 'sig_sites_p05', 'sig_sites_p10', 'rate_distributions',
	'positive_selection_detected', 'elapsed_seconds'
];

describe('fixtures/e2e/busted_*.json replay (cli.py cmd_busted, statistical bridge)', () => {
	for (const gene of ['Smc6', 'HIV1_RT']) {
		const busted = loadFixture(`e2e/busted_${gene}.json`)[0];
		const meme = loadFixture(`e2e/meme_${gene}.json`)[0];
		const lrts = Float32Array.from(meme.outputs.sites.map((s) => s.hyphaeon_lrt));
		const invariable = Uint8Array.from(meme.outputs.sites.map((s) => (s.is_invariable ? 1 : 0)));

		it(`${gene}: the meme fixture describes the same run (taxa, sites)`, () => {
			expect(busted.tolerance).toBe('1e-5');
			expect(meme.outputs.codon_count).toBe(busted.outputs.sites);
			expect(meme.outputs.taxa_count).toBe(busted.outputs.taxa);
			expect(lrts.length).toBe(busted.outputs.sites);
			// cmd_busted never writes an invariable site, so those LRTs are exactly 0 in the meme run too.
			for (let i = 0; i < lrts.length; i++) if (invariable[i]) expect(lrts[i]).toBe(0);
		});

		it(`${gene}: ACAT, Simes, omnibus LRT, energy and counts`, () => {
			const rec = bustedRecord({ lrts, invariable, numTaxa: meme.outputs.taxa_count, gene, alignment: `${gene}.fasta` });
			const want = busted.outputs;
			expect(rec.total_selection_energy).toBe(want.total_selection_energy);
			expect(rec.omnibus_lrt).toBe(want.omnibus_lrt);
			expect(Math.abs(rec.p_value_acat - want.p_value_acat)).toBeLessThanOrEqual(1e-12);
			expect(Math.abs(rec.p_value_simes - want.p_value_simes)).toBeLessThanOrEqual(1e-12);
			expect(rec.sig_sites_p05).toBe(want.sig_sites_p05);
			expect(rec.sig_sites_p10).toBe(want.sig_sites_p10);
			expect(rec.taxa).toBe(want.taxa);
			expect(rec.sites).toBe(want.sites);
			expect(rec.alignment).toBe(want.alignment);
			expect(rec.gene).toBe(want.gene);
		});

		it(`${gene}: the neural fields are null, as the fixture holds them`, () => {
			const rec = bustedRecord({ lrts, invariable, numTaxa: meme.outputs.taxa_count });
			const want = busted.outputs;
			expect(rec.predicted_gene_lrt).toBeNull();
			expect(rec.selection_probability).toBeNull();
			expect(rec.synonymous_rate_variation).toBeNull();
			expect(rec.rate_distributions).toEqual(want.rate_distributions);
			expect(rec.rate_distributions.omega_1).toBe(BUSTED_OMEGA_1);
			expect(rec.rate_distributions.omega_2).toBe(BUSTED_OMEGA_2);
			expect(rec.elapsed_seconds).toBeNull();
			// The fixture nulls the verdict because it depends on selection_probability; when the ACAT
			// half alone decides (HIV1_RT, p = 0.00126 < 0.05) the verdict is true regardless of the head.
			expect(want.positive_selection_detected).toBeNull();
			expect(rec.positive_selection_detected).toBe(want.p_value_acat < 0.05 ? true : null);
		});

		it(`${gene}: record keys in the CLI's order`, () => {
			const rec = bustedRecord({ lrts, invariable, numTaxa: meme.outputs.taxa_count });
			expect(Object.keys(rec).filter((k) => k !== 'statistics')).toEqual(RECORD_KEYS);
			expect(Object.keys(busted.outputs)).toEqual(RECORD_KEYS);
		});

		it(`${gene}: a float64 sum would NOT reproduce total_selection_energy`, () => {
			let f64 = 0;
			for (let i = 0; i < lrts.length; i++) f64 += lrts[i];
			expect(Math.abs(f64 - busted.outputs.total_selection_energy)).toBeGreaterThan(1e-6);
			expect(float32Sum(lrts)).toBe(busted.outputs.total_selection_energy);
		});
	}
});

describe('test/data/omnibus/busted_stats.json (cli.py:469-484 on seeded inputs)', () => {
	it('was generated by the reference lines with numpy 2', () => {
		expect(LOCAL.reference).toMatch(/cli\.py cmd_busted/);
		expect(LOCAL.numpy.startsWith('2.')).toBe(true);
		expect(LOCAL.cases.map((c) => c.name)).toEqual([
			'random_1', 'random_7', 'random_9', 'random_130', 'random_335', 'random_1097', 'random_5000',
			'all_invariable', 'all_variable_zero_lrt', 'exactly_threshold', 'just_above_threshold',
			'huge_lrts', 'ties', 'magnitudes'
		]);
	});

	for (const c of LOCAL.cases) {
		it(`${c.name} (L=${c.inputs.lrts.length})`, () => {
			const lrts = Float32Array.from(c.inputs.lrts);
			const inv = c.inputs.invariable;
			const s = bustedStatistics(lrts, inv);
			const want = c.outputs;
			expect(s.L).toBe(lrts.length);
			expect(s.numVariable).toBe(want.num_variable);
			expect(s.pvals).toBeInstanceOf(Float64Array);
			want.pvals.forEach((p, i) => expect(Math.abs(s.pvals[i] - p), `p[${i}]`).toBeLessThanOrEqual(1e-12));
			expect(Math.abs(s.pAcat - want.p_value_acat)).toBeLessThanOrEqual(1e-12);
			expect(Math.abs(s.pSimes - want.p_value_simes)).toBeLessThanOrEqual(1e-12);
			expect(s.omnibusLrt).toBe(want.omnibus_lrt);
			expect(s.totalSelectionEnergy).toBe(want.total_selection_energy);
			expect(s.sigSitesP05).toBe(want.sig_sites_p05);
			expect(s.sigSitesP10).toBe(want.sig_sites_p10);
		});
	}

	it('the numpy pairwise order matters at L = 5000: a sequential float32 sum differs', () => {
		const c = LOCAL.cases.find((x) => x.name === 'random_5000');
		const lrts = Float32Array.from(c.inputs.lrts);
		let seq = 0;
		for (let i = 0; i < lrts.length; i++) seq = Math.fround(seq + lrts[i]);
		expect(seq).not.toBe(c.outputs.total_selection_energy);
		expect(float32Sum(lrts)).toBe(c.outputs.total_selection_energy);
	});
});

describe('unit: the pieces', () => {
	it('variableSiteIndices is np.where(~inv)[0]', () => {
		expect(Array.from(variableSiteIndices([1, 0, 0, 1]))).toEqual([1, 2]);
		expect(Array.from(variableSiteIndices([true, false]))).toEqual([1]);
		expect(Array.from(variableSiteIndices(new Uint8Array(0)))).toEqual([]);
	});

	it('float32Sum accumulates in float32 (1e8 + 1 - 1e8 is 0, not 1)', () => {
		expect(float32Sum([1e8, 1, -1e8])).toBe(0);
		expect(float32Sum([])).toBe(0);
		expect(float32Sum(Float32Array.from([0.1, 0.2]))).toBe(Math.fround(Math.fround(0.1) + Math.fround(0.2)));
		expect(totalSelectionEnergy([1, 2, 3])).toBe(6);
	});

	it('omnibusLrt subtracts float32(3.841) and clamps at 0 before summing', () => {
		expect(BUSTED_LRT_THRESHOLD).toBe(3.841);
		expect(omnibusLrt([0, 1, 3.841])).toBe(0);
		const one = Math.fround(Math.fround(5.841) - Math.fround(3.841));
		expect(omnibusLrt([5.841])).toBe(one);
		expect(omnibusLrt([5.841, 0, 5.841])).toBe(Math.fround(one + one));
		expect(omnibusLrt([10], 4)).toBe(6);
	});

	it('simesP is min((L / rank) * sorted_p) clipped to [1e-15, 1]', () => {
		expect(simesP([0.9, 0.01, 0.5])).toBe((3 / 1) * 0.01);
		expect(simesP([0.5, 0.5])).toBe(Math.min((2 / 1) * 0.5, (2 / 2) * 0.5));
		expect(simesP([1e-20, 0.5])).toBe(1e-15);
		expect(simesP([1, 1, 1])).toBe(1);
		expect(simesP([0.999])).toBe(0.999);
		expect(() => simesP([])).toThrow(/zero-size/);
	});

	it('bustedStatistics runs ACAT over VARIABLE sites only, Simes over all', () => {
		const lrts = Float32Array.from([0, 6, 0, 2]);
		const inv = [1, 0, 1, 0];
		const s = bustedStatistics(lrts, inv);
		expect(Array.from(s.variableIndices)).toEqual([1, 3]);
		expect(s.pvals[0]).toBe(1);
		expect(s.pvals[2]).toBe(1);
		// The invariable p = 1 sites do not enter ACAT: combining only sites 1 and 3.
		const onlyVar = bustedStatistics(Float32Array.from([6, 2]), [0, 0]);
		expect(s.pAcat).toBe(onlyVar.pAcat);
		expect(s.pSimes).toBe(simesP(s.pvals));
		// LRT 6 -> p = 0.5 * chi2_1.sf(6) = 0.0072; LRT 2 -> 0.0787 (< 0.10, not < 0.05).
		expect(s.sigSitesP05).toBe(1);
		expect(s.sigSitesP10).toBe(2);
		expect(() => bustedStatistics([1, 2], [0])).toThrow(/invariable flags/);
	});

	it('bustedStatistics with no variable site combines ALL p-values (= 1) like the reference', () => {
		const s = bustedStatistics(Float32Array.from([0, 0, 0]), [1, 1, 1]);
		expect(s.numVariable).toBe(0);
		expect(s.pAcat).toBe(bustedStatistics(Float32Array.from([0, 0, 0]), [0, 0, 0]).pAcat);
		expect(s.pSimes).toBe(1);
		expect(s.omnibusLrt).toBe(0);
	});

	it('bustedHeadFields decodes ONNX-shaped outputs (typed arrays) into the record fields', () => {
		const f = bustedHeadFields({
			cls_prob: Float32Array.from([0.7]),
			pred_gene_lrt: Float32Array.from([12.5]),
			omega_prop: Float32Array.from([0.6, 0.3, 0.1]),
			syn_var: Float32Array.from([0.2]),
			pred_omega3: Float32Array.from([4.5]),
			pred_logp: Float32Array.from([2.0])
		});
		expect(f.selection_probability).toBe(Math.fround(0.7));
		expect(f.predicted_gene_lrt).toBe(12.5);
		expect(f.synonymous_rate_variation).toBe(Math.fround(0.2));
		expect(f.omega).toEqual([0.1, 1.0, 4.5]);
		expect(f.proportions).toEqual([Math.fround(0.6), Math.fround(0.3), Math.fround(0.1)]);
		expect(f.rate_distributions).toEqual({
			omega_1: 0.1, proportion_1: Math.fround(0.6),
			omega_2: 1.0, proportion_2: Math.fround(0.3),
			omega_3: 4.5, proportion_3: Math.fround(0.1)
		});
		expect(Object.keys(f.rate_distributions)).toEqual(['omega_1', 'proportion_1', 'omega_2', 'proportion_2', 'omega_3', 'proportion_3']);
	});

	it("bustedHeadFields keeps the reference's fallbacks (module names, sqrt_lrt, omega_vals)", () => {
		const base = { cls_prob: 0.2, syn_var: 0.1, omega_prop: [0.5, 0.25, 0.25] };
		expect(bustedHeadFields({ ...base, pred_lrt: 3 }).predicted_gene_lrt).toBe(3);
		expect(bustedHeadFields({ ...base, sqrt_lrt: 2 }).predicted_gene_lrt).toBe(4);
		expect(bustedHeadFields({ ...base }).predicted_gene_lrt).toBe(0);
		expect(bustedHeadFields({ ...base, omega_vals: [1, 1, 7] }).omega[2]).toBe(7);
		expect(bustedHeadFields({ ...base }).omega[2]).toBe(1.0);
		expect(() => bustedHeadFields({ syn_var: 1, omega_prop: [1, 0, 0] })).toThrow(/cls_prob/);
		expect(() => bustedHeadFields({ cls_prob: 1, omega_prop: [1, 0, 0] })).toThrow(/syn_var/);
		expect(() => bustedHeadFields({ cls_prob: 1, syn_var: 1, omega_prop: [1] })).toThrow(/omega_prop/);
	});

	it('bustedVerdict is p_acat < 0.05 or prob > 0.50, with null when the head is absent and ACAT does not decide', () => {
		expect(bustedVerdict(0.01, 0.1)).toBe(true);
		expect(bustedVerdict(0.2, 0.6)).toBe(true);
		expect(bustedVerdict(0.2, 0.5)).toBe(false);
		expect(bustedVerdict(0.05, 0.5)).toBe(false);
		expect(bustedVerdict(0.2, null)).toBeNull();
		expect(bustedVerdict(0.2)).toBeNull();
		expect(bustedVerdict(0.01, null)).toBe(true);
	});

	it('bustedRecord with a head fills every neural field and the verdict', () => {
		const rec = bustedRecord({
			lrts: Float32Array.from([0, 6, 0, 2]),
			invariable: [1, 0, 1, 0],
			numTaxa: 9,
			head: { cls_prob: [0.9], pred_gene_lrt: [7], omega_prop: [0.5, 0.3, 0.2], syn_var: [0.4], pred_omega3: [3] }
		});
		expect(Object.keys(rec).filter((k) => k !== 'statistics')).toEqual(RECORD_KEYS);
		expect(rec.selection_probability).toBe(0.9);
		expect(rec.predicted_gene_lrt).toBe(7);
		expect(rec.synonymous_rate_variation).toBe(0.4);
		expect(rec.rate_distributions.omega_3).toBe(3);
		expect(rec.positive_selection_detected).toBe(true);
		expect(rec.taxa).toBe(9);
		expect(rec.sites).toBe(4);
		expect(rec.alignment).toBeNull();
		expect(rec.statistics.numVariable).toBe(2);
	});

	it('exports the head graph names of export.py', () => {
		expect(BUSTED_HEAD_INPUT_NAMES).toEqual(['root_repr', 'mask']);
		expect(BUSTED_HEAD_OUTPUT_NAMES).toEqual(['cls_prob', 'pred_gene_lrt', 'omega_prop', 'syn_var', 'pred_omega3', 'pred_logp']);
		expect(BUSTED_EMBED_DIM).toBe(384);
	});
});

/** Four taxa, six codons, every site variable, no two sequences identical. */
const FASTA6 =
	'>alpha\nATGGCTAAAGAATTTTGG\n>beta\nATTGGTAGAGGATATTGT\n>gamma\nATGGCTAAAGAATTTTGT\n>delta\nATTGGTAGAGGATATTGG\n';
const TREE4 = '((gamma:0.1,delta:0.2):0.05,(beta:0.3,alpha:0.15):0.02);';
/** Three codons with the middle one variable only (assemble.test.js's panel: mask [1, 0, 1]). */
const FASTA3 = '>alpha\nATGTTATCA\n>beta\nATGCTATCA\n>gamma\nATGTTAAGC\n>delta\nATGGGGTCA\n';

describe('gatherSiteBatch', () => {
	it('is siteBatch for the listed sites, in the listed order', () => {
		const loaded = loadAlignmentAndTree(FASTA6, TREE4);
		expect(loaded.L).toBe(6);
		const g = gatherSiteBatch(loaded, [4, 1]);
		const b4 = siteBatch(loaded, 4, 1);
		const b1 = siteBatch(loaded, 1, 1);
		for (const name of ['msa_codons', 'msa_aas', 'dist_matrix', 'mds_coords']) {
			expect(g[name].dims[0]).toBe(2);
			expect(g[name].dims.slice(1)).toEqual(b4[name].dims.slice(1));
			const half = g[name].data.length / 2;
			expect(Array.from(g[name].data.subarray(0, half))).toEqual(Array.from(b4[name].data));
			expect(Array.from(g[name].data.subarray(half))).toEqual(Array.from(b1[name].data));
		}
		expect(g.msa_codons.data).toBeInstanceOf(BigInt64Array);
		expect(gatherSiteBatch(loaded, []).msa_codons.dims).toEqual([0, 4, 1]);
	});
});

describe('runBusted (cli.py:433-484 over callbacks)', () => {
	it('runs the variable sites only, ascending, in batches, and clamps the LRTs', async () => {
		const loaded = loadAlignmentAndTree(FASTA6, TREE4);
		expect(Array.from(loaded.invariable)).toEqual([0, 0, 0, 0, 0, 0]);
		const calls = [];
		const progress = [];
		const E = 4;
		const model = {
			predictSites: async (bundle, info) => {
				calls.push(Array.from(info.siteIndices));
				expect(bundle.msa_codons.dims).toEqual([info.count, 4, 1]);
				expect(info.N).toBe(4);
				const lrt = Float32Array.from(info.siteIndices, (s) => (s === 2 ? -0.5 : s + 0.25));
				const root_repr = new Float32Array(info.count * E);
				for (let k = 0; k < info.count; k++) for (let e = 0; e < E; e++) root_repr[k * E + e] = info.siteIndices[k] * 10 + e;
				return { lrt, root_repr };
			},
			predictHead: async (input) => {
				expect(input.dims).toEqual([1, 6, E]);
				expect(input.L).toBe(6);
				expect(input.embedDim).toBe(E);
				expect(input.mask).toBeInstanceOf(Uint8Array);
				expect(Array.from(input.mask)).toEqual([0, 0, 0, 0, 0, 0]);
				expect(input.root_repr[2 * E + 3]).toBe(23);
				return { cls_prob: [0.6], pred_gene_lrt: [8], omega_prop: [0.7, 0.2, 0.1], syn_var: [0.3], pred_omega3: [2.5] };
			}
		};
		const rec = await runBusted(loaded, model, { batchSize: 4, gene: 'g', alignment: 'a.fasta', progress: (d, t) => progress.push([d, t]) });
		expect(calls).toEqual([[0, 1, 2, 3], [4, 5]]);
		expect(progress).toEqual([[4, 6], [6, 6]]);
		expect(Array.from(rec.lrts)).toEqual([0.25, 1.25, 0, 3.25, 4.25, 5.25]);
		expect(rec.lrts).toBeInstanceOf(Float32Array);
		expect(rec.root_repr.length).toBe(6 * E);
		expect(rec.selection_probability).toBe(0.6);
		expect(rec.rate_distributions.omega_3).toBe(2.5);
		expect(rec.positive_selection_detected).toBe(true);
		expect(rec.gene).toBe('g');
		expect(rec.alignment).toBe('a.fasta');
		expect(rec.taxa).toBe(4);
		expect(rec.sites).toBe(6);
		expect(rec.total_selection_energy).toBe(float32Sum(rec.lrts));
		expect(rec.head.cls_prob).toEqual([0.6]);
	});

	it('leaves invariable sites at LRT 0 and hidden_all zero there; skips the head when asked', async () => {
		const loaded = loadAlignmentAndTree(FASTA3, TREE4);
		expect(Array.from(loaded.invariable)).toEqual([1, 0, 1]);
		const seen = [];
		const model = {
			predictSites: async (_bundle, info) => {
				seen.push(Array.from(info.siteIndices));
				return { lrt: [7.5], root_repr: Float32Array.from([1, 2, 3]) };
			},
			predictHead: null
		};
		const rec = await runBusted(loaded, model);
		expect(seen).toEqual([[1]]);
		expect(Array.from(rec.lrts)).toEqual([0, 7.5, 0]);
		expect(Array.from(rec.root_repr)).toEqual([0, 0, 0, 1, 2, 3, 0, 0, 0]);
		expect(rec.head).toBeNull();
		expect(rec.selection_probability).toBeNull();
		expect(rec.p_value_acat).toBe(bustedStatistics(rec.lrts, loaded.invariable).pAcat);
		expect(rec.statistics.numVariable).toBe(1);
	});

	it('with no variable site never calls predictSites and hands the head zeros of the default width', async () => {
		const loaded = loadAlignmentAndTree('>a\nATGATG\n>b\nATGATG\n>c\nATGATG\n>d\nATGATG\n', TREE4.replace(/gamma|delta|beta|alpha/g, (m) => ({ gamma: 'c', delta: 'd', beta: 'b', alpha: 'a' })[m]), { pruneDuplicates: false });
		expect(Array.from(loaded.invariable)).toEqual([1, 1]);
		let headInput = null;
		const rec = await runBusted(loaded, {
			predictSites: async () => { throw new Error('must not be called'); },
			predictHead: async (input) => { headInput = input; return { cls_prob: [0.1], pred_gene_lrt: [0], omega_prop: [1, 0, 0], syn_var: [0] }; }
		});
		expect(headInput.dims).toEqual([1, 2, BUSTED_EMBED_DIM]);
		expect(headInput.root_repr.length).toBe(2 * BUSTED_EMBED_DIM);
		expect(rec.total_selection_energy).toBe(0);
		expect(rec.p_value_acat).toBe(bustedStatistics([0, 0], [1, 1]).pAcat);
		expect(rec.positive_selection_detected).toBe(false);
	});

	it('rejects a predictSites result of the wrong size', async () => {
		const loaded = loadAlignmentAndTree(FASTA6, TREE4);
		await expect(runBusted(loaded, { predictSites: async () => ({ lrt: [1] }) })).rejects.toThrow(/returned 1 LRTs/);
		await expect(runBusted(loaded, { predictSites: async (_b, i) => ({ lrt: new Float32Array(i.count), root_repr: new Float32Array(5) }) })).rejects.toThrow(/root_repr/);
	});
});
