/**
 * WHY THIS FILE EXISTS
 *
 * Replays every case of fixtures/stats/*.json (generated by scripts/gen_fixtures.py from
 * hyphaeon/stats.py:16-84) against src/stats.js: `pvals_from_lrt_meme`, `pvals_from_lrt_self_liang`
 * and, through the Python-named re-exports, `benjamini_hochberg` and `cauchy_combination_p` (whose
 * kernel replay lives in numeric-stats.test.js; here they prove the re-exported bindings are the
 * same functions). The fixture class is 1e-9 (fixtures/README.md); the assertions hold that AND
 * record the measured worst case, which is at float64 rounding level.
 *
 * DTYPE IS PART OF THE CASE, as in numeric-stats.test.js: cases named `float32*` were generated
 * from float32 arrays and are replayed with a Float32Array. For the two p-value functions this
 * changes nothing (scipy promotes to float64), which the replay confirms.
 *
 * The cmd_meme cast sequence (`memeSitePq`, cli.py:99-100) is checked against the e2e fixtures'
 * `p_value`/`q_value`, which ARE those float32 casts of the reference's float64 statistics: from
 * the fixture's own float32 LRTs the port must land on the same float32 p and q for every site.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { pvalsFromLrtMeme, pvalsFromLrtSelfLiang, benjaminiHochberg, cauchyCombinationP, memeSitePq } from '../src/stats.js';
import { benjaminiHochberg as kernelBh } from '../src/numeric/bh.js';
import { cauchyCombination as kernelCct } from '../src/numeric/cauchy.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const load = (rel) => JSON.parse(readFileSync(join(ROOT, 'fixtures', rel), 'utf8'));

/** fixtures/README.md: NaN and infinities are the strings "NaN", "Infinity", "-Infinity". */
const num = (v) => (v === 'Infinity' ? Infinity : v === '-Infinity' ? -Infinity : v === 'NaN' ? NaN : v);
const numbers = (list, f32) => (f32 ? Float32Array : Float64Array).from(list.map(num));

function replay(file, fn, description) {
	describe(`fixtures/stats/${file} replay (${description})`, () => {
		const cases = load(`stats/${file}`);
		it('has the ten cases the manifest records', () => {
			expect(cases.map((c) => c.name)).toEqual([
				'zeros', 'single_zero', 'single_positive', 'empty', 'ties', 'small_and_negative', 'typical', 'huge',
				'random_exponential_200', 'float32_model_like',
			]);
		});
		for (const c of cases) {
			it(`${c.name} (n=${c.inputs.lrts.length}, ${c.tolerance})`, () => {
				expect(c.tolerance).toBe('1e-9');
				const lrts = numbers(c.inputs.lrts, c.name.startsWith('float32'));
				const got = fn(lrts);
				expect(got).toBeInstanceOf(Float64Array);
				expect(got.length).toBe(c.outputs.pvals.length);
				let worst = 0;
				c.outputs.pvals.forEach((want, i) => {
					const w = num(want);
					const diff = Math.abs(got[i] - w);
					expect(diff, `p[${i}] lrt=${lrts[i]} got ${got[i]} want ${w}`).toBeLessThanOrEqual(1e-9);
					worst = Math.max(worst, diff);
				});
				// Measured: float64 special-function agreement, three orders below the class.
				expect(worst).toBeLessThanOrEqual(1e-12);
			});
		}
	});
}

replay('pvals_from_lrt_meme.json', pvalsFromLrtMeme, 'hyphaeon/stats.py:16-32');
replay('pvals_from_lrt_self_liang.json', pvalsFromLrtSelfLiang, 'hyphaeon/stats.py:34-48');

describe('the atom at zero (stats.py:27-28, :45-46)', () => {
	it('MEME: anything not strictly positive — zero, negative zero, negative, NaN — is exactly 2/3', () => {
		const p = pvalsFromLrtMeme([0, -0, -1e-9, -5, NaN]);
		for (const v of p) expect(v).toBe(2 / 3);
	});
	it('Self-Liang: the same inputs are exactly 1', () => {
		const p = pvalsFromLrtSelfLiang([0, -0, -1e-9, -5, NaN]);
		for (const v of p) expect(v).toBe(1);
	});
	it('positive LRTs take the continuous tail, decreasing in LRT', () => {
		const p = pvalsFromLrtMeme([1e-12, 0.5, 3.84, 10, 100, Infinity]);
		for (let i = 1; i < p.length; i++) expect(p[i]).toBeLessThan(p[i - 1]);
		expect(p[0]).toBeLessThan(2 / 3);
		expect(p[p.length - 1]).toBe(0);
		expect(pvalsFromLrtSelfLiang([3.841])[0]).toBeCloseTo(0.025, 4);
	});
	it('accepts any ArrayLike and always returns float64', () => {
		expect(pvalsFromLrtMeme(Float32Array.from([2.5]))[0]).toBe(pvalsFromLrtMeme([Math.fround(2.5)])[0]);
		expect(pvalsFromLrtMeme([])).toHaveLength(0);
		expect(pvalsFromLrtSelfLiang(new Float32Array(0))).toBeInstanceOf(Float64Array);
	});
});

describe('re-exports under the Python names', () => {
	it('benjaminiHochberg and cauchyCombinationP are the kernel bindings', () => {
		expect(benjaminiHochberg).toBe(kernelBh);
		expect(cauchyCombinationP).toBe(kernelCct);
	});
	const inputArray = (c) => (c.name.startsWith('float32') ? Float32Array : Float64Array).from(c.inputs.pvals.map(num));
	for (const c of load('stats/benjamini_hochberg.json')) {
		it(`benjamini_hochberg.json ${c.name}`, () => {
			const got = benjaminiHochberg(inputArray(c));
			c.outputs.qvals.forEach((want, i) => expect(Math.abs(got[i] - want)).toBeLessThanOrEqual(1e-9));
		});
	}
	for (const c of load('stats/cauchy_combination_p.json')) {
		it(`cauchy_combination_p.json ${c.name}`, () => {
			expect(Math.abs(cauchyCombinationP(inputArray(c)) - c.outputs.p_cct)).toBeLessThanOrEqual(1e-9);
		});
	}
});

describe('memeSitePq — the cmd_meme float32 cast sequence (cli.py:99-100)', () => {
	for (const name of ['meme_Smc6', 'meme_bat_oas1', 'meme_HIV1_RT', 'meme_camelid', 'meme_RHO']) {
		it(`${name}: float32 p and q from the fixture's float32 LRTs match the CLI's written values`, () => {
			const sites = load(`e2e/${name}.json`)[0].outputs.sites;
			const lrts = Float32Array.from(sites.map((s) => s.hyphaeon_lrt));
			// The fixture LRTs are float32 values printed as float64: the cast must be lossless.
			sites.forEach((s, i) => expect(lrts[i]).toBe(s.hyphaeon_lrt));
			const { pvals, qvals } = memeSitePq(lrts);
			expect(pvals).toBeInstanceOf(Float32Array);
			expect(qvals).toBeInstanceOf(Float32Array);
			let worstP = 0;
			let worstQ = 0;
			let exact = 0;
			sites.forEach((s, i) => {
				worstP = Math.max(worstP, Math.abs(pvals[i] - s.p_value));
				worstQ = Math.max(worstQ, Math.abs(qvals[i] - s.q_value));
				if (pvals[i] === s.p_value && qvals[i] === s.q_value) exact++;
			});
			// Measured bit-exact on all 2228 sites of the five fixtures (one float32 ulp at 2/3 is 6e-8).
			expect(worstP).toBe(0);
			expect(worstQ).toBe(0);
			expect(exact).toBe(sites.length);
		});
	}
	it('q is BH of the float32 p, not of the float64 p', () => {
		const lrts = Float32Array.from([0, 1.5, 3.9, 7.2, 12.5, 0.4, 2.2]);
		const { pvals, qvals } = memeSitePq(lrts);
		expect(Array.from(qvals)).toEqual(Array.from(Float32Array.from(benjaminiHochberg(pvals))));
		expect(Array.from(pvals)).toEqual(Array.from(Float32Array.from(pvalsFromLrtMeme(lrts))));
	});
});
