"""
WHY THIS FILE EXISTS

One table, and it is the one ../../../fixtures/ cannot hold.

`fixtures/<module>/<function>.json` records what a REFERENCE FUNCTION returns (fixtures/README.md:
"`outputs` are the return values"). The four date parsers of the time-aware pillars therefore live
there, generated by `scripts/gen_fixtures.py --only dates`:

    parse_date_to_decimal        hyphaeon/temporal.py:73-151   -> fixtures/dates/parse_date_to_decimal.json
    extract_date_from_string     hyphaeon/temporal.py:196-245  -> fixtures/dates/extract_date_from_string.json
    parse_header_timestamp       hyphaeon/dating.py:317-364    -> fixtures/dates/parse_header_timestamp.json
    _parse_timestamp_flexible    hyphaeon/dating.py:367-384    -> fixtures/dates/_parse_timestamp_flexible.json

The table THIS file writes has no reference function behind it. `js/src/dates.js` makes the
hard-coded 1959 anchor opt-in (quirk Q1 in its header: `if 'Z59' in name or 'ZR59' in name or '1959'
in name: return 1959.5`, dating.py:330-332, an unbounded substring test that overwrites a real date
and claims an unrelated accession), so the port's DEFAULT path needs a reference of its own — and
that reference is `parse_header_timestamp` with step 1 skipped, which is not a function anybody can
call. `_without_1959` below is the reference's steps 2-6, in the reference's own order, over the
reference's own `extract_date_from_string`; it is the only hand-written parse in either generator,
and it is why `js/test/dates.test.js` can replay BOTH directions. A port that quietly kept the
anchor on and a port that quietly dropped the whole rule both fail there.

Everything it needs it imports from the generator: `load_date_reference` (the `ast` lift that
executes the reference functions without importing torch — hyphaeon/temporal.py:42 imports it at
module scope and the parsers use none of it) and `HEADER_TIMESTAMP_NAMES` (the same inputs
fixtures/dates/parse_header_timestamp.json records), so the two tables can never drift apart.

Regenerate from js/ with a Python that has numpy and pandas (no torch, no weights, no model):

    python test/data/dates/gen.py [--engine ../]

Output: parsers.json in this directory. NaN and infinities are written as the strings "NaN",
"Infinity", "-Infinity" (the fixtures/README.md convention).
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import math
import re
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent


def load_generator(engine_root: Path):
    """`scripts/gen_fixtures.py` of the given checkout, by path: it is a script, not a package."""
    path = engine_root / "scripts" / "gen_fixtures.py"
    spec = importlib.util.spec_from_file_location("hyphaeon_gen_fixtures", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def jsonable(v):
    if isinstance(v, (np.floating, float)):
        f = float(v)
        if math.isnan(f):
            return "NaN"
        if math.isinf(f):
            return "Infinity" if f > 0 else "-Infinity"
        return f
    if isinstance(v, (np.integer, int)) and not isinstance(v, bool):
        return int(v)
    if isinstance(v, (list, tuple)):
        return [jsonable(x) for x in v]
    if isinstance(v, dict):
        return {str(k): jsonable(x) for k, x in v.items()}
    return v


def _without_1959(name, ns):
    """
    parse_header_timestamp (dating.py:334-364) with step 1 skipped.

    Steps 2-6 of the reference, in the reference's order, over the reference's own
    `extract_date_from_string`. Nothing else here is retyped; this is, because there is no reference
    function that answers the question "what would the header rules say if the anchor were not
    there?" and that is exactly what js/src/dates.js answers by default.
    """
    if not name:
        return np.nan
    d = ns["extract_date_from_string"](name)
    if not np.isnan(d):
        return d
    m_korber = re.search(r"^[A-Za-z](\d{2})[A-Za-z]{2}[._]", name)
    if m_korber:
        yr_short = int(m_korber.group(1))
        return float(1900 + yr_short if yr_short >= 30 else 2000 + yr_short) + 0.5
    m_pipe = re.search(r"_(?:[A-Z]{2})_(\d{2})_", name)
    if m_pipe:
        yr_short = int(m_pipe.group(1))
        return float(1900 + yr_short if yr_short >= 30 else 2000 + yr_short) + 0.5
    m_wpi = re.search(r"(\d+(?:\.\d+)?)\s*(?:WPI|wpi)", name)
    if m_wpi:
        return float(m_wpi.group(1))
    m_dpi = re.search(r"(\d+(?:\.\d+)?)\s*(?:DPI|dpi)", name)
    if m_dpi:
        return float(m_dpi.group(1))
    return np.nan


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--engine",
        default=str(HERE.parents[3]),
        help="root of the HyphAeon checkout holding hyphaeon/temporal.py (default: this repository)",
    )
    args = ap.parse_args(argv)
    engine_root = Path(args.engine).resolve()

    gen = load_generator(engine_root)
    ns, provenance = gen.load_date_reference(engine_root)

    payload = {
        "generated_by": "js/test/data/dates/gen.py",
        "source": provenance,
        "python": ".".join(str(x) for x in sys.version_info[:3]),
        "numpy": np.__version__,
        # The same inputs fixtures/dates/parse_header_timestamp.json records, with the anchor's step
        # removed. The two tables are compared case for case in js/test/dates.test.js: the names the
        # answers differ on are exactly the names the anchor claims.
        "parse_header_timestamp_without_1959": [
            {"input": v, "output": _without_1959(v, ns)} for v in gen.HEADER_TIMESTAMP_NAMES
        ],
    }

    path = HERE / "parsers.json"
    path.write_text(json.dumps(jsonable(payload), indent=1) + "\n")
    print(f"wrote {path.relative_to(HERE.parents[3])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
