/**
 * WHY THIS FILE EXISTS
 *
 * The special functions that hyphaeon/*.py gets from scipy and that a browser does not have:
 *
 *   - `scipy.stats.chi2.sf`            stats.py:29,47 (MEME and Self–Liang mixture p-values)
 *   - `scipy.stats.t.sf`               epistasis.py:171, phenotype.py:461,579 (Student-t p-values)
 *   - `scipy.stats.norm.sf`            phenotype.py:530
 *   - `scipy.stats.hypergeom.cdf`      filter.py:78 (patch scan, `1 - cdf(k-1, L, K, d)`)
 *
 * Each of those is a thin wrapper over one of three classical special functions — the regularized
 * incomplete gamma (χ²), the regularized incomplete beta (Student t) and the complementary error
 * function (normal) — plus an exact hypergeometric sum. This file implements those in float64 and
 * exposes the scipy-shaped wrappers so the ports read like the Python they mirror. The reference
 * values the tests replay come from scipy 1.16 / numpy 2.3 (js/test/data/numeric/gen.py); the
 * fixture tolerance class for everything here is 1e-9 (fixtures/README.md), and the local tests
 * hold it to 1e-12 relative so that class has margin.
 *
 * WHAT IT DELIBERATELY DOES NOT DO. It does not port cephes or Boost; it implements the textbook
 * algorithms (Numerical Recipes `gser`/`gcf`/`betacf`, Cody's rational erfc, Lanczos log-gamma) and
 * measures them against scipy. Nothing here touches a model, an array of LRTs or a p-value policy:
 * the mixture nulls in stats.py belong to the stats port, not the kernel.
 *
 * MEASUREMENTS BEHIND THE CONSTANTS AND CHOICES:
 *
 *   - Lanczos coefficients are Numerical Recipes 3rd ed. `gammln` (g = 671/128, 14 terms), which
 *     gives Γ to ~1e-15 relative over x > 0. Absolute error in lgamma grows like eps·x·ln x from
 *     the (x + 0.5)·ln(t) − t cancellation, exactly as in scipy's own `gammaln`, so lgamma itself
 *     agrees with scipy to 1.4e-14 relative on the grid (worst at x = 1.9, next to the zero at 2).
 *     That growth is what makes a NAIVE incomplete-gamma prefactor exp(a·ln x − x − lgamma(a))
 *     lose digits at large a: measured against the scipy grid, the naive form's worst point is
 *     1.03e-12 relative (gammaincReg(1000, 600)); the Stirling-series form used here for a ≥ 10,
 *     a·[ln(x/a) − (x/a − 1)] + ½ln(a/2π) − S(a), brings the worst point to 4.6e-13
 *     (gammaincc(1000, 2000), where the continued fraction's ~1000 iterations dominate). The
 *     log-beta prefactor uses the matching fold (Boost's ibeta_power_terms split); its worst grid
 *     point is 1.6e-13 (betaincReg(100, 10, 0.001)). The 1e-12 test bound therefore has ≥ 2×
 *     margin everywhere, and the fixture class (1e-9) three orders.
 *   - Hypergeometric pmf/cdf/sf sum the support with terms generated by the ratio recurrence from
 *     the mode and normalised by their total, rather than exp(logChoose − logChoose) per term.
 *     Measured on the (M = 3000, n = 120, N = 35) support against scipy (Boost): a pure-lgamma
 *     log-choose route is off by up to 4.1e-12 relative per term (three lgamma values near 2·10⁴
 *     cancelling), the exact-integer log-choose path 2.7e-14, the recurrence route 9.8e-16.
 *     `logChoose` is still exported for callers that want the log domain.
 *   - erfc is Cody (1969) / netlib CALERF, whose three rational segments (|x| ≤ 0.46875, ≤ 4, > 4)
 *     were fitted to 18–19 significant digits; the exp(−x²) factor is split as
 *     exp(−⌊16x⌋²/256)·exp(−(x − ⌊16x⌋/16)(x + ⌊16x⌋/16)) exactly as CALERF does, because that
 *     split is worth ~2 decimal digits in the tail. Against scipy's cephes `erfc` the grid agrees
 *     to 4e-16 relative (worst at x = 3.99) down to erfc(26.5) ≈ 1e-307; normSf's worst point is
 *     1.7e-13 at z = 30 and is cephes' own exp(−z²/2) rounding as much as this file's.
 *   - Student t forms x = df/(df+t²) and y = t²/(df+t²) separately and hands both to the beta
 *     routine: forming y as 1 − x loses ~|log10 y| digits when t is tiny (measured: 3e-11 relative
 *     at t = 1e-6, df = 1 against scipy; 1.5e-13 after the split, worst at t = 2.5, df = 2000).
 *
 * ARGUMENT CONVENTIONS follow scipy: `chi2Sf(x, df)`, `tSf(t, df)`, `hypergeomPmf(k, M, n, N)`
 * with M the population size, n the number of success states and N the number of draws.
 * Non-integer k in the hypergeometric functions behaves as scipy 1.16 does (measured, not
 * assumed): pmf is 0; cdf/sf are exactly 0 / 1 below and above the support, and NaN for a
 * non-integer k INSIDE the support (Boost's hypergeometric rejects it; rv_discrete's bounds check
 * runs first). Integer k outside the support: pmf 0, cdf exactly 0 / 1, sf exactly 1 / 0.
 */

const LN_SQRT_2PI = 0.9189385332046727417803297; // ln(sqrt(2π))
const SQRT_2 = Math.SQRT2;
const EPS = 2.220446049250313e-16;
const FPMIN = Number.MIN_VALUE / EPS; // NR's "number near the smallest representable"
const MAX_ITER = 100000;
// cephes MAXLOG: scipy's igam_fac and erfc return exactly 0 (never a denormal) once the exponent
// of the underlying exp(−x²) / exp(a ln x − x − lgamma a) falls below this; mirrored so the deep
// tails agree exactly rather than to within a denormal. Measured: scipy erfc(26.64) = 1.29e-310,
// erfc(26.65) = 0; gammaincc(0.5, 740) = 0 where e⁻⁷⁴⁰ ≈ 4e-322 would still be representable.
const MAXLOG = 709.782712893384;

// ---------------------------------------------------------------------------------------------
// log-gamma
// ---------------------------------------------------------------------------------------------

/** Numerical Recipes 3rd ed. gammln coefficients, g = 671/128. */
const LANCZOS_COEF = [
	57.1562356658629235, -59.5979603554754912, 14.1360979747417471, -0.491913816097620199,
	0.339946499848118887e-4, 0.465236289270485756e-4, -0.983744753048795646e-4,
	0.158088703224912494e-3, -0.210264441724104883e-3, 0.217439618115212643e-3,
	-0.164318106536763890e-3, 0.844182239838527433e-4, -0.261908384015814087e-4,
	0.368991826595316234e-5,
];

/**
 * ln Γ(x) for x > 0 by the Lanczos approximation (NR3 `gammln`), reflection for x < 0.5.
 * Returns ln|Γ(x)| for negative non-integers (as scipy.special.gammaln does) and +Infinity at
 * 0 and the negative integers. lgamma(1) and lgamma(2) are returned as exactly 0.
 *
 * @param {number} x
 * @returns {number}
 */
export function lgamma(x) {
	if (Number.isNaN(x)) return NaN;
	if (x === 1 || x === 2) return 0;
	if (x === Infinity) return Infinity;
	if (x <= 0) {
		if (Number.isInteger(x)) return Infinity;
		// Reflection: Γ(x)Γ(1−x) = π / sin(πx).
		const s = Math.abs(sinPi(x));
		return Math.log(Math.PI / s) - lgamma(1 - x);
	}
	if (x < 0.5) {
		const s = Math.abs(sinPi(x));
		return Math.log(Math.PI / s) - lgamma(1 - x);
	}
	let y = x;
	const tmp0 = x + 5.2421875; // x + g + 0.5, g = 671/128
	const tmp = (x + 0.5) * Math.log(tmp0) - tmp0;
	let ser = 0.999999999999997092;
	for (let j = 0; j < 14; j++) ser += LANCZOS_COEF[j] / ++y;
	return tmp + Math.log((2.5066282746310005 * ser) / x);
}

/** sin(πx) with the argument reduced exactly, so it is accurate for large |x|. */
function sinPi(x) {
	let r = x % 2;
	if (r < 0) r += 2;
	if (r === 0 || r === 1) return 0;
	if (r === 0.5) return 1;
	if (r === 1.5) return -1;
	return Math.sin(Math.PI * r);
}

/**
 * Stirling correction S(x) = lgamma(x) − [(x − ½)ln x − x + ½ ln 2π], for x ≥ 10.
 * Terms through x⁻¹⁵; the first omitted term is ≈ 0.18·x⁻¹⁷ < 2e-18 at x = 10.
 */
const STIRLING = [
	1 / 12, -1 / 360, 1 / 1260, -1 / 1680, 1 / 1188, -691 / 360360, 1 / 156, -3617 / 122400,
];
function stirlingCorrection(x) {
	const inv2 = 1 / (x * x);
	let acc = STIRLING[STIRLING.length - 1];
	for (let i = STIRLING.length - 2; i >= 0; i--) acc = STIRLING[i] + inv2 * acc;
	return acc / x;
}

/**
 * ln(r) − (r − 1) for r > 0 without cancellation. For r in [½, 2], r − 1 is exact (Sterbenz) and
 * the atanh series in z = (r−1)/(r+1) is used; outside, the direct form has no cancellation
 * because |ln r| is not small. (Taking log1p(u) with u = r − 1 formed by the caller is NOT
 * equivalent: at r = 4e-10 the rounded u = −1 + 4e-10 has lost 7 digits of r — measured as a 2e-6
 * relative error in gammaincReg(25, 1e-8) before this split.)
 */
function logRatioMinus(r) {
	if (r < 0.5 || r > 2) return Math.log(r) - (r - 1);
	const u = r - 1;
	const z = u / (2 + u);
	const z2 = z * z;
	// ln(1+u) = 2 atanh(z) = 2(z + z³/3 + z⁵/5 + …); 2z − u = −u²/(2+u) exactly.
	let sum = 0;
	let term = z * z2; // z³
	for (let k = 3; k < 200; k += 2) {
		const add = term / k;
		sum += add;
		if (Math.abs(add) < Math.abs(sum) * EPS * 0.5) break;
		term *= z2;
	}
	return -(u * u) / (2 + u) + 2 * sum;
}

/** ln(r) for r > 0 with r given as a ratio p/q whose difference p − q the caller can form exactly. */
function logRatio(p, q, diff) {
	const r = p / q;
	if (r < 0.5 || r > 2) return Math.log(r);
	return Math.log1p(diff / q);
}

/**
 * ln B(a, b) = lgamma(a) + lgamma(b) − lgamma(a + b), with the large-argument cancellation
 * removed (see the header). a, b > 0.
 */
function logBeta(a, b) {
	if (a < b) {
		const t = a;
		a = b;
		b = t;
	}
	// now a >= b
	if (b >= 10) {
		// Both large: (a−½)ln(a/(a+b)) + (b−½)ln(b/(a+b)) − ½ln(a+b) + ½ln2π + S(a)+S(b)−S(a+b)
		return (
			-(a - 0.5) * Math.log1p(b / a) -
			(b - 0.5) * Math.log1p(a / b) -
			0.5 * Math.log(a + b) +
			LN_SQRT_2PI +
			stirlingCorrection(a) +
			stirlingCorrection(b) -
			stirlingCorrection(a + b)
		);
	}
	if (a >= 10) {
		// lgamma(a+b) − lgamma(a) = (a−½)log1p(b/a) + b(ln(a+b) − 1) + S(a+b) − S(a)
		const diff =
			(a - 0.5) * Math.log1p(b / a) +
			b * (Math.log(a + b) - 1) +
			stirlingCorrection(a + b) -
			stirlingCorrection(a);
		return lgamma(b) - diff;
	}
	return lgamma(a) + lgamma(b) - lgamma(a + b);
}

// ---------------------------------------------------------------------------------------------
// regularized incomplete gamma
// ---------------------------------------------------------------------------------------------

/**
 * exp(a ln x − x − lgamma(a)), the common prefactor of P(a, x) and Q(a, x). For a ≥ 10 the
 * exponent is formed as a·[ln(x/a) − (x/a − 1)] + ½ln(a/2π) − S(a), which has no cancellation
 * between O(a ln a) terms; for a < 10 the naive form is accurate enough (all terms < 30).
 */
function gammaPrefactor(a, x) {
	let ax;
	if (a >= 10) {
		ax = a * logRatioMinus(x / a) + 0.5 * Math.log(a) - LN_SQRT_2PI - stirlingCorrection(a);
	} else {
		ax = a * Math.log(x) - x - lgamma(a);
	}
	if (ax < -MAXLOG) return 0; // cephes igam_fac underflow rule, see MAXLOG
	return Math.exp(ax);
}

/** Series for P(a, x) (NR `gser`), valid and fast for x < a + 1. Returns P. */
function gammaSeries(a, x) {
	let ap = a;
	let sum = 1 / a;
	let del = sum;
	for (let n = 0; n < MAX_ITER; n++) {
		ap += 1;
		del *= x / ap;
		sum += del;
		if (Math.abs(del) < Math.abs(sum) * EPS) break;
	}
	return sum * gammaPrefactor(a, x);
}

/** Continued fraction for Q(a, x) (NR `gcf`, modified Lentz), valid and fast for x ≥ a + 1. */
function gammaContinuedFraction(a, x) {
	let b = x + 1 - a;
	let c = 1 / FPMIN;
	let d = 1 / b;
	let h = d;
	for (let i = 1; i < MAX_ITER; i++) {
		const an = -i * (i - a);
		b += 2;
		d = an * d + b;
		if (Math.abs(d) < FPMIN) d = FPMIN;
		c = b + an / c;
		if (Math.abs(c) < FPMIN) c = FPMIN;
		d = 1 / d;
		const del = d * c;
		h *= del;
		if (Math.abs(del - 1) < EPS) break;
	}
	return h * gammaPrefactor(a, x);
}

/**
 * Regularized lower incomplete gamma P(a, x) = γ(a, x) / Γ(a) — scipy.special.gammainc.
 *
 * @param {number} a shape, > 0
 * @param {number} x ≥ 0
 * @returns {number}
 */
export function gammaincReg(a, x) {
	if (Number.isNaN(a) || Number.isNaN(x) || a <= 0 || x < 0) return NaN;
	if (x === 0) return 0;
	if (x === Infinity) return 1;
	if (x < a + 1) return gammaSeries(a, x);
	return 1 - gammaContinuedFraction(a, x);
}

/**
 * Regularized upper incomplete gamma Q(a, x) = Γ(a, x) / Γ(a) — scipy.special.gammaincc.
 *
 * @param {number} a shape, > 0
 * @param {number} x ≥ 0
 * @returns {number}
 */
export function gammaincc(a, x) {
	if (Number.isNaN(a) || Number.isNaN(x) || a <= 0 || x < 0) return NaN;
	if (x === 0) return 1;
	if (x === Infinity) return 0;
	if (x < a + 1) return 1 - gammaSeries(a, x);
	return gammaContinuedFraction(a, x);
}

// ---------------------------------------------------------------------------------------------
// regularized incomplete beta
// ---------------------------------------------------------------------------------------------

/** NR `betacf`: continued fraction for I_x(a, b), modified Lentz. */
function betaContinuedFraction(a, b, x) {
	const qab = a + b;
	const qap = a + 1;
	const qam = a - 1;
	let c = 1;
	let d = 1 - (qab * x) / qap;
	if (Math.abs(d) < FPMIN) d = FPMIN;
	d = 1 / d;
	let h = d;
	for (let m = 1; m < MAX_ITER; m++) {
		const m2 = 2 * m;
		let aa = (m * (b - m) * x) / ((qam + m2) * (a + m2));
		d = 1 + aa * d;
		if (Math.abs(d) < FPMIN) d = FPMIN;
		c = 1 + aa / c;
		if (Math.abs(c) < FPMIN) c = FPMIN;
		d = 1 / d;
		h *= d * c;
		aa = (-(a + m) * (qab + m) * x) / ((a + m2) * (qap + m2));
		d = 1 + aa * d;
		if (Math.abs(d) < FPMIN) d = FPMIN;
		c = 1 + aa / c;
		if (Math.abs(c) < FPMIN) c = FPMIN;
		d = 1 / d;
		const del = d * c;
		h *= del;
		if (Math.abs(del - 1) < EPS) break;
	}
	return h;
}

/**
 * ln[x^a y^b / B(a, b)], the prefactor of the continued fraction. When both a, b ≥ 10 the
 * Stirling forms of lgamma are folded into the powers:
 *   a·ln(xc/a) + b·ln(yc/b) + ½ln(ab/(2πc)) − [S(a) + S(b) − S(a+b)],  c = a + b,
 * with ln(xc/a) = log1p((xb − ya)/a) when xc/a is within [½, 2] (Boost's ibeta_power_terms uses
 * the same split) and the direct log otherwise, so nothing of size a·ln a cancels and a tiny x
 * keeps its digits. Otherwise a ln x + b ln y − logBeta(a, b).
 */
function logBetaPrefix(a, b, x, y) {
	if (a >= 10 && b >= 10) {
		const c = a + b;
		const l1 = logRatio(x * c, a, x * b - y * a); // ln(xc/a); xc − a = xb − ya
		const l2 = logRatio(y * c, b, y * a - x * b); // ln(yc/b)
		return (
			a * l1 +
			b * l2 +
			0.5 * Math.log((a * b) / c) -
			LN_SQRT_2PI -
			(stirlingCorrection(a) + stirlingCorrection(b) - stirlingCorrection(c))
		);
	}
	return a * Math.log(x) + b * Math.log(y) - logBeta(a, b);
}

/**
 * I_x(a, b) given both x and y = 1 − x, each formed accurately by the caller. Forming y inside
 * from a rounded x loses ~|log10(y)| digits of y when x → 1 (tSf at t = 1e-6 was off by 3e-11
 * relative that way, measured against scipy); tSf forms df/(df+t²) and t²/(df+t²) directly.
 */
function betaincXY(a, b, x, y) {
	if (x === 0) return 0;
	if (y === 0) return 1;
	const logPrefix = logBetaPrefix(a, b, x, y);
	const bt = logPrefix < -745.2 ? 0 : Math.exp(logPrefix);
	if (x < (a + 1) / (a + b + 2)) return (bt * betaContinuedFraction(a, b, x)) / a;
	return 1 - (bt * betaContinuedFraction(b, a, y)) / b;
}

/**
 * Regularized incomplete beta I_x(a, b) — scipy.special.betainc.
 *
 * NR `betai`: the continued fraction is evaluated directly when x < (a + 1)/(a + b + 2) and by
 * the symmetry I_x(a, b) = 1 − I_{1−x}(b, a) otherwise, so it always converges quickly.
 *
 * @param {number} a > 0
 * @param {number} b > 0
 * @param {number} x in [0, 1]
 * @returns {number}
 */
export function betaincReg(a, b, x) {
	if (Number.isNaN(a) || Number.isNaN(b) || Number.isNaN(x) || a <= 0 || b <= 0 || x < 0 || x > 1) return NaN;
	return betaincXY(a, b, x, 1 - x);
}

// ---------------------------------------------------------------------------------------------
// complementary error function (Cody 1969, netlib specfun CALERF)
// ---------------------------------------------------------------------------------------------

const ERF_A = [3.1611237438705656, 113.864154151050156, 377.485237685302021, 3209.37758913846947, 0.185777706184603153];
const ERF_B = [23.6012909523441209, 244.024637934444173, 1282.61652607737228, 2844.23683343917062];
const ERF_C = [
	0.564188496988670089, 8.88314979438837594, 66.1191906371416295, 298.635138197400131, 881.95222124176909,
	1712.04761263407058, 2051.07837782607147, 1230.33935479799725, 2.15311535474403846e-8,
];
const ERF_D = [
	15.7449261107098347, 117.693950891312499, 537.181101862009858, 1621.38957456669019, 3290.79923573345963,
	4362.61909014324716, 3439.36767414372164, 1230.33935480374942,
];
const ERF_P = [0.305326634961232344, 0.360344899949804439, 0.125781726111229246, 0.0160837851487422766, 6.58749161529837803e-4, 0.0163153871373020978];
const ERF_Q = [2.56852019228982242, 1.87295284992346725, 0.527905102951428412, 0.0605183413124413191, 2.33520497626869185e-3];
const ERF_SQRPI = 0.56418958354775628695; // 1/sqrt(π)
const ERF_THRESH = 0.46875;
const ERF_XSMALL = 1.11e-16;

/**
 * Complementary error function erfc(x) = 1 − erf(x) — scipy.special.erfc.
 *
 * @param {number} x
 * @returns {number}
 */
export function erfc(x) {
	if (Number.isNaN(x)) return NaN;
	const y = Math.abs(x);
	let result;
	if (y <= ERF_THRESH) {
		let ysq = 0;
		if (y > ERF_XSMALL) ysq = y * y;
		let xnum = ERF_A[4] * ysq;
		let xden = ysq;
		for (let i = 0; i < 3; i++) {
			xnum = (xnum + ERF_A[i]) * ysq;
			xden = (xden + ERF_B[i]) * ysq;
		}
		const erf = (x * (xnum + ERF_A[3])) / (xden + ERF_B[3]);
		return 1 - erf;
	}
	if (y <= 4) {
		let xnum = ERF_C[8] * y;
		let xden = y;
		for (let i = 0; i < 7; i++) {
			xnum = (xnum + ERF_C[i]) * y;
			xden = (xden + ERF_D[i]) * y;
		}
		result = (xnum + ERF_C[7]) / (xden + ERF_D[7]);
	} else {
		if (y === Infinity || y * y > MAXLOG) return x < 0 ? 2 : 0; // cephes underflow rule, see MAXLOG
		const ysq = 1 / (y * y);
		let xnum = ERF_P[5] * ysq;
		let xden = ysq;
		for (let i = 0; i < 4; i++) {
			xnum = (xnum + ERF_P[i]) * ysq;
			xden = (xden + ERF_Q[i]) * ysq;
		}
		result = (ysq * (xnum + ERF_P[4])) / (xden + ERF_Q[4]);
		result = (ERF_SQRPI - result) / y;
	}
	const ysq16 = Math.trunc(y * 16) / 16;
	const del = (y - ysq16) * (y + ysq16);
	result = Math.exp(-ysq16 * ysq16) * Math.exp(-del) * result;
	if (x < 0) result = 2 - result;
	return result;
}

// ---------------------------------------------------------------------------------------------
// scipy.stats-shaped wrappers
// ---------------------------------------------------------------------------------------------

/**
 * χ² survival function P[X > x] for df degrees of freedom — scipy.stats.chi2.sf(x, df).
 * chi2Sf(x, df) = Q(df/2, x/2). Negative x gives 1 (scipy: x below the support).
 *
 * @param {number} x
 * @param {number} df > 0
 * @returns {number}
 */
export function chi2Sf(x, df) {
	if (Number.isNaN(x) || Number.isNaN(df) || df <= 0) return NaN;
	if (x <= 0) return 1;
	return gammaincc(df / 2, x / 2);
}

/**
 * χ² cumulative distribution P[X ≤ x] — scipy.stats.chi2.cdf(x, df).
 *
 * @param {number} x
 * @param {number} df > 0
 * @returns {number}
 */
export function chi2Cdf(x, df) {
	if (Number.isNaN(x) || Number.isNaN(df) || df <= 0) return NaN;
	if (x <= 0) return 0;
	return gammaincReg(df / 2, x / 2);
}

/**
 * Student-t survival function P[T > t] — scipy.stats.t.sf(t, df).
 * For t > 0: ½·I_{df/(df+t²)}(df/2, ½); for t < 0: 1 − tSf(−t, df); tSf(0) = ½ exactly.
 *
 * @param {number} t
 * @param {number} df > 0
 * @returns {number}
 */
export function tSf(t, df) {
	if (Number.isNaN(t) || Number.isNaN(df) || df <= 0) return NaN;
	if (t === Infinity) return 0;
	if (t === -Infinity) return 1;
	if (t < 0) return 1 - tSf(-t, df);
	if (t === 0) return 0.5;
	const t2 = t * t;
	const s = df + t2;
	// x = df/(df+t²) and y = t²/(df+t²) are each formed directly (see betaincXY); one route only —
	// an explicit "1 − I_y(½, df/2)" small-t branch was measured to lose 1e-11 relative at t = 5,
	// df = 500 and to underflow to 0 at t = 10, df = 500 (want 6.9e-22), so it was removed.
	return 0.5 * betaincXY(df / 2, 0.5, df / s, t2 / s);
}

/**
 * Student-t cumulative distribution P[T ≤ t] — scipy.stats.t.cdf(t, df); tCdf(t) = tSf(−t).
 *
 * @param {number} t
 * @param {number} df > 0
 * @returns {number}
 */
export function tCdf(t, df) {
	return tSf(-t, df);
}

/**
 * Standard normal survival function P[Z > z] = ½·erfc(z/√2) — scipy.stats.norm.sf(z).
 *
 * @param {number} z
 * @returns {number}
 */
export function normSf(z) {
	return 0.5 * erfc(z / SQRT_2);
}

/**
 * Standard normal cumulative distribution P[Z ≤ z] = ½·erfc(−z/√2) — scipy.stats.norm.cdf(z).
 *
 * @param {number} z
 * @returns {number}
 */
export function normCdf(z) {
	return 0.5 * erfc(-z / SQRT_2);
}

// ---------------------------------------------------------------------------------------------
// combinatorics and the hypergeometric distribution
// ---------------------------------------------------------------------------------------------

/**
 * ln C(n, k) = lgamma(n+1) − lgamma(k+1) − lgamma(n−k+1). −Infinity when k < 0 or k > n.
 * Real-valued n and k are accepted (the gamma form); the fast exact path is used for integers with
 * min(k, n−k) ≤ 64, where a compensated sum of ln((n−k+i)/i) is accurate to ~1e-15 absolute.
 *
 * @param {number} n ≥ 0
 * @param {number} k
 * @returns {number}
 */
export function logChoose(n, k) {
	if (Number.isNaN(n) || Number.isNaN(k)) return NaN;
	if (k < 0 || k > n) return -Infinity;
	if (Number.isInteger(n) && Number.isInteger(k)) {
		const m = Math.min(k, n - k);
		if (m === 0) return 0;
		if (m <= 64) {
			let sum = 0;
			let comp = 0;
			for (let i = 1; i <= m; i++) {
				const term = Math.log((n - m + i) / i);
				const y = term - comp;
				const t = sum + y;
				comp = t - sum - y;
				sum = t;
			}
			return sum;
		}
	}
	return lgamma(n + 1) - lgamma(k + 1) - lgamma(n - k + 1);
}

/**
 * The hypergeometric support and normalised pmf over it, generated by the ratio recurrence from
 * the mode (see header). `pmf[i]` is P[X = lo + i].
 *
 * pmf(k+1)/pmf(k) = (n − k)(N − k) / ((k + 1)(M − n − N + k + 1)).
 */
function hypergeomTable(M, n, N) {
	const lo = Math.max(0, N - (M - n));
	const hi = Math.min(n, N);
	const size = hi - lo + 1;
	const pmf = new Float64Array(size);
	// Mode: floor((N + 1)(n + 1) / (M + 2)), clamped into the support.
	let mode = Math.floor(((N + 1) * (n + 1)) / (M + 2));
	if (mode < lo) mode = lo;
	if (mode > hi) mode = hi;
	pmf[mode - lo] = 1;
	for (let k = mode; k < hi; k++) {
		const r = ((n - k) * (N - k)) / ((k + 1) * (M - n - N + k + 1));
		pmf[k + 1 - lo] = pmf[k - lo] * r;
	}
	for (let k = mode; k > lo; k--) {
		const r = (k * (M - n - N + k)) / ((n - k + 1) * (N - k + 1));
		pmf[k - 1 - lo] = pmf[k - lo] * r;
	}
	// Normalise; sum smallest-first from each side of the mode for accuracy.
	let total = 0;
	for (let i = 0; i < mode - lo; i++) total += pmf[i];
	let upper = 0;
	for (let i = size - 1; i > mode - lo; i--) upper += pmf[i];
	total += upper + 1;
	for (let i = 0; i < size; i++) pmf[i] /= total;
	return { lo, hi, pmf };
}

function hypergeomArgsValid(M, n, N) {
	return (
		Number.isInteger(M) && Number.isInteger(n) && Number.isInteger(N) && M >= 0 && n >= 0 && n <= M && N >= 0 && N <= M
	);
}

/**
 * Hypergeometric pmf P[X = k] — scipy.stats.hypergeom.pmf(k, M, n, N).
 *
 * @param {number} k successes drawn
 * @param {number} M population size
 * @param {number} n success states in the population
 * @param {number} N draws
 * @returns {number}
 */
export function hypergeomPmf(k, M, n, N) {
	if (!hypergeomArgsValid(M, n, N) || Number.isNaN(k)) return NaN;
	if (!Number.isInteger(k)) return 0;
	const { lo, hi, pmf } = hypergeomTable(M, n, N);
	if (k < lo || k > hi) return 0;
	return pmf[k - lo];
}

/**
 * Hypergeometric cdf P[X ≤ k] — scipy.stats.hypergeom.cdf(k, M, n, N). Non-integer k inside the
 * support gives NaN (scipy 1.16 behaviour, see header).
 *
 * @param {number} k
 * @param {number} M population size
 * @param {number} n success states
 * @param {number} N draws
 * @returns {number}
 */
export function hypergeomCdf(k, M, n, N) {
	if (!hypergeomArgsValid(M, n, N) || Number.isNaN(k)) return NaN;
	const { lo, hi, pmf } = hypergeomTable(M, n, N);
	if (k < lo) return 0;
	if (k >= hi) return 1;
	if (!Number.isInteger(k)) return NaN;
	let s = 0;
	for (let i = 0; i <= k - lo; i++) s += pmf[i];
	return s;
}

/**
 * Hypergeometric survival P[X > k] — scipy.stats.hypergeom.sf(k, M, n, N). Non-integer k inside
 * the support gives NaN (scipy 1.16 behaviour, see header).
 *
 * @param {number} k
 * @param {number} M population size
 * @param {number} n success states
 * @param {number} N draws
 * @returns {number}
 */
export function hypergeomSf(k, M, n, N) {
	if (!hypergeomArgsValid(M, n, N) || Number.isNaN(k)) return NaN;
	const { lo, hi, pmf } = hypergeomTable(M, n, N);
	if (k < lo) return 1;
	if (k >= hi) return 0;
	if (!Number.isInteger(k)) return NaN;
	let s = 0;
	for (let i = pmf.length - 1; i > k - lo; i--) s += pmf[i];
	return s;
}
